### PR TITLE
Adds new integration [macxq/foxess-ha]

### PR DESCRIPTION
**Pull request by macxq**
Monitor you photovoltaic installation with FoxESS inverter directly from HA

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass <https://hacs.xyz/docs/publish/include#before-submitting>

**Comment by macxq** [comment]
@ludeeus Ci passed :)

**Comment by macxq** [comment]
@ludeeus any chance to push this forward :D ?

**Review by macxq — COMMENTED** [review]
CI is passing

**Pull request merged**
