### PR TITLE
Adds new plugin [Brianfit/xkcd-card-ha]

### PR DESCRIPTION
**Pull request by Brianfit**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [ ] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/Brianfit/xkcd-card-ha>
Link to successful HACS action (without the `ignore` key): <https://github.com/Brianfit/xkcd-card-ha/actions/runs/7850988379>
Link to successful hassfest action (if integration): <>

### CODE REVIEW

**Comment by tjorim** [comment]
Not alphabetically sorted.

**Comment by Brianfit** [comment]
@tjorim My bad. I thought the convention was capital letters follow all lower case listings, I see it now. Should I close and resubmit?

**Comment by tjorim** [comment]
You can just update your PR. Change and commit it to the patch-3 branch on your fork.

**Comment by Brianfit** [comment]
Newby here, as I read this, a review by a reviewer with write access is the next step, and I just have to wait for that, is that correct? Just want to be sure I'm not missing a step! And thank you all for your volunteer service! 🙏

**Comment by Brianfit** [comment]
Waiting, waiting, waiting. Today marks THREE MONTHS since I've submitted this. I've been using this card every day and it's been installed by a number of other HA users who love it. Please can I get a review pretty please? 🫶 I promise it'll be a hit!

**Review by Brianfit — COMMENTED** [review]
Done.

**Pull request merged**
