### PR TITLE
Adds new plugin [fineemb/lovelace-air-filter-card]

### PR DESCRIPTION
**Pull request by fineemb**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by fineemb** [comment]
> is this Xiaomi specific or a generic Air Filter (Purifier) Card ?

This is based on Xiaomi

**Comment by fineemb** [comment]
Currently only tested on Xiaomi devices, other devices are uncertain

**Comment by fineemb** [comment]
It is not very difficult to apply to other devices, but I have not tested the environment
Maybe I should explain it in the README

**Comment by GeorgeSG** [comment]
Not sure why I was tagged as a reviewer so I won't be approving/rejecting this, but I'd add my two cents.

The card looks great and it'd be awesome if you can make it a bit more generic so it can work with more devices!

I don't have a Xiaomi filter, but I have a Philips one ([integration](https://github.com/xMrVizzy/philips-airpurifier)). I tried it and it doesn't work right now, but it could with some small changes. Here are my suggestions:
1. The card breaks if you pass less than 3 `modes`. This is not documented, but ideally, it should work with any number of modes. IMO This is the most important fix, because I think it'll break even with Xiaomi devices.
2. You can make the `aqi` property configurable. My purifier has a `pm25` attribute. Adding a config option for `aqi_attribute` that defaults to `aqi` will enable more devices to use this card
3. Same for speeds/modes - it has hardcoded ` this.modes = ["auto","silent","strong"]` and I don't think it'll use others, even if you pass them as config. For example, my Filter's auto mode value is "Auto Mode".

**Comment by ludeeus** [comment]
> Not sure why I was tagged as a reviewer so I won't be approving/rejecting this, but I'll add my two cents.

@GeorgeSG This is why (which is just rude):
image

**Pull request merged**
