### PR TITLE
Adds new plugin [madmicio/LG-WebOS-Remote-Control]

### PR DESCRIPTION
**Pull request by madmicio**
please consider the possibility to insert remote control for Lg Tv based on WebOs System in the list of official plugin repositories.
thank you in advance
Maurizio

Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
@ludeeus correct me if I'm wrong, but it seems like failing check do not use information from `hacs.json` (`filename` and `content_in_root`).

**Comment by ludeeus** [comment]
That is correct @PiotrMachowski , @hacs-bot does not handle that, and that is one of the reasons I made an action for HACS

**Comment by domutec** [comment]
Hi madmicio, I have a question is it possible to assign channel-pad to a switch in home assistant

**Comment by KTibow** [comment]
@domutec wrong place to ask, try the community form or making an issue in that repo.

**Pull request merged**
