### PR TITLE
Adds new integration [alryaz/hass-lkcomu-interrao]

### PR DESCRIPTION
**Pull request by alryaz**
This is a submission of a functional adapter for one of the largest energy distribution conglomerates in Russia, namely **Inter RAO**.

The addon supports multiple personal cabinets, and allows indications submission and account balance and invoice information polling.

It was developed in collaboration with multiple members of the Russian Home Assistant community. It serves as a functional reference implementation of the underlying **inter-rao-energosbyt-python** API.

I would like to have it added for the ease of support as well as to ensure most limitations are eased as they appear, and bugs fixed when encountered. Community contributions and outreach is crucial to ensure further development.

_(While there are (and will be) many similar integrations in my GitHub portfolio, they serve different purposes and utilize different libraries and communication protocols. It is possible, albeit unintuitive for the end user to have them merged into one.)_

Brands repo pull request: ~[&#35;2641](https://github.com/home-assistant/brands/pull/2641)~ _(Merged)_
Wheels repo pull request: ~[&#35;437](https://github.com/home-assistant/wheels-custom-integrations/pull/437)~ _(Merged)_

### CODE REVIEW

**Comment by alryaz** [comment]
Relevant pull request: #993

**Comment by alryaz** [comment]
Updated my branch with master

**Review by jbouwh — DISMISSED** [review]
Look ok to me

**Pull request merged**
