### PR TITLE
Adds new plugin [finity69x2/fan-percent-button-row]

### PR DESCRIPTION
**Pull request by finity69x2**

### CODE REVIEW

**Comment by finity69x2** [comment]
This says it's failing on lack of images but the repository includes three .jpg image files.

I looked at the details at the "checks..." information page for images but the info there is vague.

What do I need to do to fix this check?

**Review by markgdev — APPROVED** [review]

**Review by ludeeus — CHANGES_REQUESTED** [review]
The PR is not editable by HACS maintainers

**Comment by finity69x2** [comment]
How do I fix that?

**Pull request closed without merging**
