### PR TITLE
Adds new integration [ha0y/xiaomi_miot_raw]

### PR DESCRIPTION
**Pull request by ha0y**
For the README in English for this repo: https://github.com/ha0y/xiaomi_miot_raw/blob/master/README_en.md

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
https://github.com/hacs/default/pull/801/checks?check_run_id=1858030407#step:2:455

**Comment by ha0y** [comment]
I'm sorry for requesting review by mistake. I'll close this pr and reopen one.

**Pull request closed without merging**
