### PR TITLE
Adds new integration [sbabcock23/hass-tryfi]

### PR DESCRIPTION
**Pull request by sbabcock23**
added new tryfi integration

### CODE REVIEW

**Comment by sbabcock23** [comment]
Please approve, my PRs are:
Wheels - https://github.com/home-assistant/wheels-custom-integrations/pull/174
Brands - https://github.com/home-assistant/brands/pull/1996

**Comment by KTibow** [comment]
@sbabcock23
> DO NOT REQUEST REVIEWS, THAT IS JUST RUDE, IF YOU DO THE PULL REQUEST WILL BE CLOSED!

**Comment by sbabcock23** [comment]
Ok. Just wanted to let you know that I have open PRs for the checks that are failing.

**Review by djtimca — APPROVED** [review]

**Pull request merged**
