### PR TITLE
Adds new integration [Nedevski/hass_kat_bulgaria]

### PR DESCRIPTION
**Pull request by Nedevski**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: [Link](https://github.com/Nedevski/hass_kat_bulgaria/releases/tag/0.6.2.3)
Link to successful HACS action (without the `ignore` key): [Link](https://github.com/Nedevski/hass_kat_bulgaria/actions/runs/5360519695)
Link to successful hassfest action (if integration): [Link](https://github.com/Nedevski/hass_kat_bulgaria/actions/runs/5360519692)

### CODE REVIEW

**Comment by tjorim** [comment]
country not defined in hacs.json

**Comment by Nedevski** [comment]
If I define a country, does that mean that it will not be visible for anyone that has not set Bulgaria in their instance?

**Comment by tjorim** [comment]
Not by default, I think by default ALL is selected when configuring HACS. If the user would set the country to anything besides 'all' or Bulgaria they won't see it.

**Comment by Nedevski** [comment]
Ah, so it's for metadata and filtering, rather than for hiding it. Alright then, I will add it in a bit.

**Comment by Nedevski** [comment]
Done.

**Comment by tjorim** [comment]
> > Is it a good idea to keep rebasing my PR as it falls behind, or is that potentially causing a delay in it being reviewed?
> 
> That brings your PR to the bottom of the list <https://github.com/hacs/default/pulls?page=1&q=is%3Apr+is%3Aopen+sort%3Aupdated-asc+draft%3Afalse>

**Comment by Nedevski** [comment]
@tjorim Ok, I will stop doing it then. Thank you for the info.

**Pull request merged**
