### PR TITLE
Adds new integration [shaiu/technicolor]

### PR DESCRIPTION
**Pull request by shaiu**
This is a new integration for the Technicolor Gateway

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass, and no information given to users

**Review by shaiu — COMMENTED** [review]
fixed missing delimiter

**Comment by ludeeus** [comment]
Your information is still lacking, what does it do? what type of devices does it track? what is technicolor? how do you configure it?

**Comment by shaiu** [comment]
updated README to have more information

**Comment by shaiu** [comment]
@ludeeus please have a look again. I updated the README.
Thanks.

**Comment by ludeeus** [comment]
Much better :+1:

**Pull request merged**
