### PR TITLE
Adds new integration [Makhuta/homeassistant-honeygain_scrapper]

### PR DESCRIPTION
**Pull request by Makhuta**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/Makhuta/homeassistant-honeygain_scrapper/releases/tag/v0.3.6>
Link to successful HACS action (without the `ignore` key): <https://github.com/Makhuta/homeassistant-honeygain_scrapper/actions/runs/7798778557/job/21268162386>
Link to successful hassfest action (if integration): <https://github.com/Makhuta/homeassistant-honeygain_scrapper/actions/runs/7798778552/job/21268162396>

### CODE REVIEW

**Comment by tjorim** [comment]
Is `cloud_push` the correct `iot_class` if you scrape the account?

Also wondering why the docker container is needed according to the docs if it's also written in python anyway, isn't it possible to just have the custom integration?

**Comment by Makhuta** [comment]
> Is `cloud_push` the correct `iot_class` if you scrape the account?
> 
> Also wondering why the docker container is needed according to the docs if it's also written in python anyway, isn't it possible to just have the custom integration?

Well it is possible but the connection to the original HoneyGain api can be rather slow and sometimes not so reliable and if you restart HomeAssistant (the script tries to log-in) for like 5-6 times in short time it will lock itself out for about an hour.

With the iot_class you are right I missread the description and also forgot to change it after fiddling for some time, I will change it as soon as possible, I suppose that it is not that much of the problem if it is the only change, I mean with validation if you know what I mean.

**Comment by Makhuta** [comment]
Here are the updated Links after the pointed problem fix other things are still same:

Link to current release: <https://github.com/Makhuta/homeassistant-honeygain_scrapper/releases/tag/v0.3.7>
Link to successful HACS action (without the ignore key): <https://github.com/Makhuta/homeassistant-honeygain_scrapper/actions/runs/7799340840/job/21269945898>
Link to successful hassfest action (if integration): <https://github.com/Makhuta/homeassistant-honeygain_scrapper/actions/runs/7799340836/job/21269945899>

**Comment by Makhuta** [comment]
I finally managed (and got the time) to remake the scrapper so it doesn't need the docker container here is again the updated links if they are gonna be needed:

Link to current release: <https://github.com/Makhuta/homeassistant-honeygain_scrapper/releases/tag/v1.0.0>
Link to successful HACS action (without the ignore key): <https://github.com/Makhuta/homeassistant-honeygain_scrapper/actions/runs/8216477054/job/22471084657>
Link to successful hassfest action (if integration): <https://github.com/Makhuta/homeassistant-honeygain_scrapper/actions/runs/8216477055/job/22471084656>

**Pull request closed without merging**
