### PR TITLE
Re-add xirixiz/Home-Assistant-Sensor-Afvalwijzer (fixed bug)

### PR DESCRIPTION
**Pull request by xirixiz**
Removed systemexit at:

https://github.com/xirixiz/python-afvalwijzer-afvalstoffendienst/blob/4fe9332ed2a7c7f2637251413ca74f690f9805ee/Afvaldienst/Afvaldienst.py#L53

### CODE REVIEW

**Comment by xirixiz** [comment]
Thanks for your reply, I wasn't aware of all this, especially as it was in HACS before.

Anyway, I`d rather leave it out of HACS as I`m not using it myself and don't have a lot of time to maintain it. 
Maybe someone from the community like to contribute if they like to see it in HACS.

**Comment by xirixiz** [comment]
> Are you sure this is ready for HACS?
> 
> * It's not in the right place (supposed to be in `/custom_components/Afvaldienst`, is in `/Afvaldienst`)
> * It doesn't have a manifest in the custom component folder
> * It doesn't have a HACS manifest
> * It doesn't use a lowercase naming scheme
> * And it's not in the custom wheels and brands.

Not all are true actually. Not sure where you looked at, but there is a custom_components folder, a manifest in the custom_component folder and its lowercase. Anyway, as it's not that much work, I`ll fix it nowadays.

**Comment by xirixiz** [comment]
Thanks for your help @KTibow! It's very much appreciated!

**Review by ludeeus — APPROVED** [review]
I need to run some tests before this is merged, I'm sure not if this has happened before and I'm not sure how HACS handles it.

**Comment by xirixiz** [comment]
> I need to run some tests before this is merged, I'm sure not if this has happened before and I'm not sure how HACS handles it.

I`m not sure as well, however the last release has been tested and verified without any issues, and also ofcourse  bad code regarding the HASS lockup has been replaced.

https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/4.4.0

**Comment by xirixiz** [comment]
I hope this request will be approved as the updated custom component has been confirmed working properly. Thanks!

**Comment by ludeeus** [comment]
This request is approved?
The holdoff is that I need to ensure that HACS handles it properly when it's added back.

**Review by dynasticorpheus — APPROVED** [review]

**Comment by ludeeus** [comment]
Closing this as there is a conflict and the repo is deleted so an update of the PR is not possible.

**Comment by KTibow** [comment]
@xirixiz try making another PR?

**Pull request closed without merging**
