### PR TITLE
Adds new integration [tronikos/default_config_disabler]

### PR DESCRIPTION
**Pull request by tronikos**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/tronikos/default_config_disabler/releases/tag/v0.0.1
Link to successful HACS action (without the `ignore` key): https://github.com/tronikos/default_config_disabler/actions/runs/5594386123
Link to successful hassfest action (if integration): https://github.com/tronikos/default_config_disabler/actions/runs/5594179658

### CODE REVIEW

**Comment by ludeeus** [comment]
I will not accept integrations that messes with core integrations in this way <https://github.com/tronikos/default_config_disabler/blob/main/custom_components/default_config_disabler/helpers.py#L50>

**Comment by tronikos** [comment]
Fair. It's worth mentioning this at https://hacs.xyz/docs/publish/include then. Currently it says: "Custom integrations that override core integrations will not be accepted, you can still use it as a [custom repository](https://hacs.xyz/docs/faq/custom_repositories)" Maybe change it to override or modify? I sent you https://github.com/hacs/documentation/pull/383

**Comment by ludeeus** [comment]
This is overriding the core integration.
As you are effectively changing how it behaves.

I'll look at changing the docs later if I think it's necessary.

**Comment by tronikos** [comment]
Overriding a core integration is when you have a custom integration with the same name which yes is strongly discouraged, see https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure/#:~:text=If%20you%20want%20to%20override,discourage%20overriding%20built%2Din%20integrations. Here there is no overriding. The custom integration does modify the core integration though.

**Pull request closed without merging**
