### PR TITLE
Adds new integration [catduckgnaf/ryobi_gdo]  New default repository

### PR DESCRIPTION
**Pull request by catduckgnaf**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/catduckgnaf/ryobi_gdo/releases/tag/0.20> 
Link to successful HACS action (without the `ignore` key): <https://github.com/catduckgnaf/ryobi_gdo/actions/runs/7704732026>
Link to successful hassfest action (if integration): <https://github.com/catduckgnaf/ryobi_gdo/actions/runs/7704653030>

### CODE REVIEW

**Comment by tjorim** [comment]
Is this used outside US and CA?

(There also seems to be a duplicate workflow with the ignore key present, you don't need the validate.yml as there already is hacs.yml and hassfest.yml with the required actions.)

**Comment by catduckgnaf** [comment]
> Would this integration be used outside US and CA?
> 
> (There also seems to be a duplicate workflow with the ignore key present, you don't need the validate.yml as there already is hacs.yml and hassfest.yml with the required actions.)

This would not be used outside the US or CA

I deleted the duplicate workflow.

**Comment by tjorim** [comment]
> This would not be used outside the US or CA
> 

In that case please add the country codes to your hacs.json. Check the docs for more info.

**Comment by catduckgnaf** [comment]
> country codes to your hacs.json

Thanks! added it

**Pull request closed without merging**
