### PR TITLE
Adds new integration [dermotduffy/hass-motioneye]

### PR DESCRIPTION
**Pull request by dermotduffy**
Add [hass-motioneye](https://github.com/dermotduffy/hass-motioneye) as a default HACS integration. Thank you!

### CODE REVIEW

**Review by dgomes — APPROVED** [review]

**Comment by ludeeus** [comment]
Why does this exist?
There already is a core integration for motioneye <https://www.home-assistant.io/integrations/motioneye/>

**Comment by dermotduffy** [comment]
@ludeeus Yes, and I wrote it! The core integration currently has only a fraction of the functionality of this custom component. The [long term plan](https://github.com/dermotduffy/hass-motioneye#long-term-intention) is that this custom component will not exist, but only after the there is functional parity and all the PRs are into Core. I expect this will take a considerable amount of time to happen based on code review/merge pace ... hence this custom component.

**Comment by ludeeus** [comment]
Then it should not be added as a default repository.
Folks that want to use it can still add it as custom. adding things here that is expected to be removed does not make sense.

**Comment by dermotduffy** [comment]
Adding it here exposes the expanded functionality to a wider user base by "default". That feels like a desirable outcome for users. 

Whilst it can still be explicitly added if a user already had the knowledge/intention, without being in default there's no ability for the user to "discover" that the expanded functionality even exists. HACS default showcases newly discovered custom components, and this is the win this PR offers to your users over status quo.

I wouldn't expect the removal to be for another 9 months (guessing at PR review/merge times), otherwise I wouldn't have bothered adding it here.

Will close if you remain unconvinced. Thanks for considering!

**Comment by rsnodgrass** [comment]
I agree with @dermotduffy that sometimes it just makes sense to add integrations to HACS where getting the features/functionality into core will take months or longer. In the meantime, it is great to get as many users on the newest version (via HACS) to test and rapidly innovate on functionality. Having people randomly find custom_integrations leaves this up to pure chance, as opposed to seeing them in HACS.

**Comment by RubenKelevra** [comment]
Cool! Didn't even know that this existed. Thanks for your work @dermotduffy :)

**Comment by ludeeus** [comment]
Closing this for now, if you decide to rename it feel free to open a new PR :+1:

**Pull request closed without merging**
