### PR TITLE
Adds new integration [jugla/keyatome]

### PR DESCRIPTION
**Pull request by jugla**

### CODE REVIEW

**Comment by jugla** [comment]
Hello,
I'm puzzled .
HACS action failed on HACS/default action : 
image
HACS action works on my repository (jugla/KeyAtome) : 
image

@ludeeus , @KTibow , ... Any hints ?
Thanks in advance
Philippe

**Comment by KTibow** [comment]
This isn't your fault. There's a problem with the action.

**Comment by jugla** [comment]
Thanks a lot for your quick answer @KTibow

**Comment by jugla** [comment]
Ok I have renamed the repository with lower case (as the component name).
It works in this way

**Pull request merged**
