### PR TITLE
Adds new integration [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor]

### PR DESCRIPTION
**Pull request by PiotrMachowski**
Repository: [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)

### CODE REVIEW

**Review by bieniu — APPROVED** [review]

**Review by gjohansson-ST — CHANGES_REQUESTED** [review]
No _init_ file in repository

**Comment by PiotrMachowski** [comment]
> No _init_ file in repository

Added in the latest version

**Review by pszafer — APPROVED** [review]

**Review by gjohansson-ST — APPROVED** [review]

**Comment by PiotrMachowski** [comment]
@ludeeus Thank you!

**Pull request merged**
