### PR TITLE
Removes integration [alryaz/hass-mosenergosbyt]

### PR DESCRIPTION
**Pull request by alryaz**
...in favor of its successor

### CODE REVIEW

**Comment by alryaz** [comment]
@ludeeus is it possible to include an in-place replacement for it within this pull request, or should a different one be made?

**Comment by ludeeus** [comment]
Different

**Comment by alryaz** [comment]
Relevant pull request: #995

**Review by ludeeus — CHANGES_REQUESTED** [review]
This is missing a file, please use `make remove`  <https://hacs.xyz/docs/publish/remove>

**Pull request closed without merging**
