### PR TITLE
Adds new integration [JAAlperin/hass-bardolph]

### PR DESCRIPTION
**Pull request by JAAlperin**
Before you submit a pull request, please make sure you have the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository

### CODE REVIEW

**Comment by ludeeus** [comment]
How much is left before I can add it?
Currently, it's on hold until these tasks are complete.
image

**Comment by JAAlperin** [comment]
All of these are satisfied.  It has been tested as a custom for three weeks with at least three updates.  All OK.

Regards,

Jeff Alperin

H: 561-666-7789
C: 561-797-9876

**Comment by ludeeus** [comment]
You still need to check them.

**Comment by JAAlperin** [comment]
Thank you, Joakim.

Hopefully, I got it right this time.

Regards,

Jeff Alperin

H: 561-666-7789
C: 561-797-9876

**Pull request closed without merging**
