### PR TITLE
Adds new integration [AlexandrErohin/home-assistant-flightradar24]

### PR DESCRIPTION
**Pull request by AlexandrErohin**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/AlexandrErohin/home-assistant-flightradar24/releases/tag/v1.15.1
Link to successful HACS action (without the `ignore` key): https://github.com/AlexandrErohin/home-assistant-flightradar24/actions/runs/10720151188
Link to successful hassfest action (if integration): https://github.com/AlexandrErohin/home-assistant-flightradar24/actions/runs/10720151174

### CODE REVIEW

**Comment by tjorim** [comment]
https://github.com/AlexandrErohin/home-assistant-flightradar24/blob/main/custom_components/flightradar24/manifest.json#L7
-> `iot_class` is not `local_polling` as it requires an active internet connection:
https://developers.home-assistant.io/docs/creating_integration_manifest/#iot-class

**Comment by AlexandrErohin** [comment]
@tjorim Thank you!
I have fixed it and edited the links for the current release, HACS action and hassfest action

**Comment by AlexandrErohin** [comment]
@ludeeus Hi, Could you tell me what I need to do to have this PR merged? Thanks

**Comment by tjorim** [comment]
For starters, have patience and read the docs: https://experimental.hacs.xyz/docs/publish/include#after-submitting. "HACS contains a significant number of repos, with new repositories added almost daily. Check the [backlog](https://github.com/hacs/default/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+sort%3Acreated-asc) before querying your PR."

Looks like your PR is currently at place 79 or something. With about 6 PRs being merged per week, give it a week or 13-14. Also, don't mention people, it's annoying for them and won't speed things up.

**Comment by AlexandrErohin** [comment]
Thank you!

**Pull request merged**
