### PR TITLE
Adds new integration [TomBrien/cardiffwaste-ha]

### PR DESCRIPTION
**Pull request by TomBrien**
Adds Cardiff Waste integration (a basic next collection set of sensors). [Link to passing hassfest and HACS actions](https://github.com/TomBrien/cardiffwaste-ha/actions).

Blank line change at EOF is the joy of editing on GH. Let me know if you want it removing

### CODE REVIEW

**Comment by TomBrien** [comment]
I'm unsure why https://github.com/hacs/default/pull/1207/commits/f036c3d12919e3e534caab2f327eb79a0e819e63  failed when https://github.com/hacs/default/pull/1207/commits/7c3bf41646d5996546a0a4edde11d1a8b2a01da2 passed

**Comment by ludeeus** [comment]
[TomBrien/cardiffwastepy](https://github.com/TomBrien/cardiffwastepy) is not something HACS can track.

**Comment by TomBrien** [comment]
Yeah my bad copied and pasted the wrong repo when changing

**Comment by ludeeus** [comment]
The data in this integration is only available for users in a specific country, you should add `country` to <https://github.com/TomBrien/cardiffwaste-ha/blob/main/hacs.json>
<https://hacs.xyz/docs/publish/start#hacsjson>

**Comment by TomBrien** [comment]
Done in https://github.com/TomBrien/cardiffwaste-ha/pull/15

**Pull request merged**
