### PR TITLE
Adds new integration [nagyrobi/home-assistant-custom-components-linkplay]

### PR DESCRIPTION
**Pull request by nagyrobi**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by ludeeus** [comment]
Why is this not a fork, when it clearly is a fork of <https://github.com/Limych/media_player.linkplay>?

**Comment by nagyrobi** [comment]
> Why is this not a fork, when it clearly is a fork of https://github.com/Limych/media_player.linkplay?

It was a fork originally, but it failed in the HACS check system detecting it as a fork. It only passed that check if I imported it as a stand alone repository. Seems that HACS doesn't accept forks anymore (I have other component submitted in HACS several months ago, back then it didn't ckeck fork status).

**Comment by ludeeus** [comment]
> Seems that HACS doesn't accept forks anymore

It does... it's there in the documentation... It's preferred over this

**Comment by nagyrobi** [comment]
I'm sorry I dont't quite understand. It didn't pass the check while it was a fork. What was I supposed to do?

**Comment by ludeeus** [comment]
Ignore the check, since the documentation states that it can fail.

**Comment by nagyrobi** [comment]
I'm sorry in the docs it's not specified that a PR can pass through with a failed check. People usually think that all checks have to pass, unless stated otherwise. I didn't see a mention of this in the docs.

**Comment by nagyrobi** [comment]
So what do you want me to do now in order for this to be accepted?

**Comment by nagyrobi** [comment]
OK re-added this as a fork now. Please review.

**Pull request merged**
