### PR TITLE
Adds new integration [basnijholt/adaptive-lighting]

### PR DESCRIPTION
**Pull request by RubenKelevra**
This is a successor to https://github.com/hacs/default/pull/671, which was declined due to the open PR for adding adaptive-lighting as a core component. Since this PR was withdrawn I think it's fine to add it to the hacs default repositories.

### CODE REVIEW

**Comment by ludeeus** [comment]
You are not the owner and your contributions to that repo are not considered major, it's great that you want to help out but I can't accept this PR from you

<https://hacs.xyz/docs/publish/include>
> Only the owner of the repository or a major contributor to it can submit a PR to have it included as a default.

**Comment by RubenKelevra** [comment]
@basnijholt can you please approve this PR :)

**Review by basnijholt — COMMENTED** [review]
Thanks a lot for doing this!

**Comment by basnijholt** [comment]
@ludeeus could you reopen this PR?

**Comment by jbouwh** [comment]
need to rebase

**Review by jbouwh — DISMISSED** [review]
The owner is not an issue

**Comment by RubenKelevra** [comment]
The bot messed up the title :/

**Comment by RubenKelevra** [comment]
@jbouwh wrote:
> need to rebase

done

**Review by jbouwh — APPROVED** [review]

**Comment by RubenKelevra** [comment]
@ludeeus can you have another look, please? :)

**Pull request merged**
