### PR TITLE
Adds new integration [gazoodle/gecko-home-assistant]

### PR DESCRIPTION
**Pull request by gazoodle**

### CODE REVIEW

**Comment by KTibow** [comment]
Would you mind resolving the conflicts @gazoodle?

**Comment by gazoodle** [comment]
> Would you mind resolving the conflicts @gazoodle?

I’m waiting for the HA team to merge my PR, so it’s currently out of my hands as I understand it. 

https://github.com/home-assistant/wheels-custom-integrations/pull/209

**Comment by KTibow** [comment]
You could try re-requesting a review.

**Comment by gazoodle** [comment]
> You could try re-requesting a review.

The associated HA wheels PR was approved so there should be no blocks remaining for this PR to get merged.

**Pull request merged**
