### PR TITLE
Adds new integration [TarheelGrad1998/files]

### PR DESCRIPTION
**Pull request by TarheelGrad1998**
File Component is a prerequisite for the Gallery Card.

### CODE REVIEW

**Comment by TarheelGrad1998** [comment]
No idea what to do for Brands....this is stand alone.

**Comment by KTibow** [comment]
Recreate this PR?
image

**Comment by TarheelGrad1998** [comment]
I merged, does that fix it?

**Comment by KTibow** [comment]
Yup, it did.

**Pull request closed without merging**
