### PR TITLE
Adds new plugin [htmltiger/numberbox-card]

### PR DESCRIPTION
**Pull request by htmltiger**
Please add this
[https://community.home-assistant.io/t/addon-input-number-with-and-buttons-to-replace-slider](https://community.home-assistant.io/t/addon-input-number-with-and-buttons-to-replace-slider)

### CODE REVIEW

**Comment by KTibow** [comment]
Your link is broken

**Comment by maxwroc** [comment]
I'm signing off this PR as adding your repo via hacs and installation was successful. Although I have found few issues:

* There was a wrong path in the lovelace configuration in your README (I've sent PR with the fix).

* Looks like the name doesn't show up by default (when there is no `name` setting)

* Name setting seems to be not respected at all - setting it to `true` doesn't help nor putting a string there

* Clicked/tapped button stays highlighted until you click somewhere else 

image

**Review by maxwroc — APPROVED** [review]

**Comment by htmltiger** [comment]
> I'm signing off this PR as adding your repo via hacs and installation was successful. Although I have found few issues:
> 
> * There was a wrong path in the lovelace configuration in your README (I've sent PR with the fix).
> * Looks like the name doesn't show up by default (when there is no `name` setting)
> * Name setting seems to be not respected at all - setting it to `true` doesn't help nor putting a string there
> * Clicked/tapped button stays highlighted until you click somewhere else
> 

The name works fine here (Home Assistant 0.116.4)
https://imgur.com/N52LKv9
Will need to work on button focus blur.

Thanks

**Comment by KTibow** [comment]
@htmltiger they meant that it should grab the `friendly_name` from the entity, so you don't have to manually put a name in config.

**Comment by htmltiger** [comment]
> @htmltiger they meant that it should grab the `friendly_name` from the entity, so you don't have to manually put a name in config.

it does that already
https://imgur.com/D89cJTG

**Comment by KTibow** [comment]
Aaah, got it. Thanks for clarifying.

**Comment by maxwroc** [comment]
It wasn't working for me. In the example I have pasted the name wasn't showing at all regardless if name property was specified, was true/false or set to done text.

I'm on 116.4 too and tested it on Chrome PC/Android

**Comment by maxwroc** [comment]
Ok I have taken a look what is going on. You have the condition where you don't render name if there is no icon. Since I haven't set icon explicitly and it wasn't available via attributes nothing was showing up except the +/- and value.
These are the attributes of the entity:
image

One more thing which is just an advice/suggestion:  your card is being re-rendered on every hass update - which happens quite often. The reason is that _hass and stateObj are on the list of tracked properties and they are being set every time. Even though these objects might be the same as previous (same properties and values) they are not the same instance. So when LitElement is doing simple comparison "==" to check whether update is required it always re-render it. 
To make it working correctly you have two options:
* Implement shouldUpdate function where you will be checking if the actual update is needed
* Remove hass and stateObj from tracked properties and use only simple properties as tracked ones (like strings/numbers/bools)

IMO the second approach is better. Anyway this is just a hint - if you want to make it better

**Comment by htmltiger** [comment]
> Ok I have taken a look what is going on. You have the condition where you don't render name if there is no icon. Since I haven't set icon explicitly and it wasn't available via attributes so nothing was showing up except the +/- and value.
> These are the attributes of the entity:
> 
> One more thing which is just an advice/suggestion: your card is being re-rendered on every hass update - which happens quite often. The reason is that _hass and stateObj are on the list of tracked properties and they are being set every time. Even though these objects might be the same as previous (same properties and values) they are not the same instance. So when LitElement is doing simple comparison "==" to check whether update is required it always re-render it.
> To make it working correctly you have two options:
> 
> * Implement shouldUpdate function where you will be checking if the actual update is needed
> * Remove hass and stateObj from tracked properties and use only simple properties as tracked ones (like strings/numbers/bools)
> 
> IMO the second approach is better. Anyway this is just a hint - if you want to make it better

I have updated it to display name even if icon is none, 
also added shouldUpdate function so now it only renders if changed.
Thanks for the feedback.

**Pull request merged**
