### PR TITLE
Adds new integration [PepegaBruh/CryptoTracker]

### PR DESCRIPTION
**Pull request by PepegaBruh**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass

**Comment by gjohansson-ST** [comment]
No point in running recheck until the brands requirement has been approved

**Comment by PepegaBruh** [comment]
So, now the icon for the custom component has been added to the brand repositories and I have also added the iot class to my manifest, I think now all the CI can pass

**Pull request merged**
