### PR TITLE
Adds new integration [cathiele/homeassistant-goecharger]

### PR DESCRIPTION
**Pull request by cathiele**
Integration for the go-eCharger (smart wallbox for electric vehicles)

### CODE REVIEW

**Review by Bouni — APPROVED** [review]
Looks good

**Comment by Bouni** [comment]
@ludeeus What's the prefered way to get people to review a PR?
As it takes 3 people to review a PR this is quite a challenge ...

**Comment by ludeeus** [comment]
TBH... just wait for me to finish moving so I get some time to do this.

**Comment by Bouni** [comment]
Ok, thanks for clarification, wasn't aware that you're moving 👍🏽

**Pull request merged**
