### PR TITLE
Adds new integration [jellespijker/home-assistant-ultimaker]

### PR DESCRIPTION
**Pull request by jellespijker**
Added jellespijker/home-assistant-ultimaker
Integration for Ultimaker 3D printers

### CODE REVIEW

**Comment by jellespijker** [comment]
Ultimaker brand logo and icons are awaiting approval of PR home-assistant/brands#2150

**Review by wowgamr — APPROVED** [review]
Looks like it's ok 👍

**Review by DCSBL — APPROVED** [review]

**Review by msekoranja — APPROVED** [review]

**Comment by jellespijker** [comment]
Manifest was missing a __version__ key and automatic checks became more strict. Added minimum version of `2021.1.0` to the manifest.

**Comment by DCSBL** [comment]
Keep in mind that version is referring to the integration version, not the minimum HA version. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions

**Comment by jellespijker** [comment]
@DCSBL Good catch. Thank you. Will change it!

**Pull request merged**
