### PR TITLE
Adds new integration [ikxdf/flux_led-home-assistant]

### PR DESCRIPTION
**Pull request by ikxdf**
patch-1

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

**Comment by Danielhiversen** [comment]
Any reason for not fixing the official integration?

**Comment by ikxdf** [comment]
> Any reason for not fixing the official integration?

Sorry but is a very old version fixed by me one years ago. I don know if my fix is valid for master and i don't know if it is well written.
I have tryied to add my personal fix to HACS because i'm testing the procedure.
If you want add my fix to master you can do that. The fix is about timing for Magic Home device like led stips. At the moment in original HA flux_led component is not working about 1 or 2 years.

**Comment by ikxdf** [comment]
> Any reason for not fixing the official integration?

added to official integration

**Comment by ludeeus** [comment]
Closing as CI does not pass, and PR to have this in core has been opened.

**Pull request closed without merging**
