### PR TITLE
Adds new plugin [turbulator/pandora-cas-card]

### PR DESCRIPTION
**Pull request by turbulator**

### CODE REVIEW

**Review by JonahKr — APPROVED** [review]
Generally LGTM 
@turbulator i cannot chack if the images are licensed, especially as they are just base64 encoded png raw files which are hardcoded.

**Review by ludeeus — CHANGES_REQUESTED** [review]
README is not in English, which makes it only useful to a part of the world, add the country key to the hacs.json file as you did for the integration

**Comment by turbulator** [comment]
You are absolutely right. I've just added country section in hacs.json.

**Pull request merged**
