### PR TITLE
Adds new integration [kodi1/meteoalarm]

### PR DESCRIPTION
**Pull request by kodi1**
Before you submit a pull request, please make sure you have the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository

### CODE REVIEW

**Comment by ludeeus** [comment]
What is the difference between this and https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/meteoalarm ?

**Comment by kodi1** [comment]
It's rely on xml api, which is not reliable in my region.

**Comment by ludeeus** [comment]
Why have a custom_component and not submit a PR to Home Assistant with the changes?
Also, your README should state the difference between them.

**Comment by kodi1** [comment]
Component parse meteoalarm page, which is totally different in HA.

**Pull request merged**
