### PR TITLE
Adds new integration [py-smart-gardena/hass-gardena-smart-system]

### PR DESCRIPTION
**Pull request by grm**
Before you submit a pull request, please make sure you have done the following:

- [X] You are submitting only 1 repository.
- [X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X] You have tested it with HACS by adding it as a custom repository.
- [X] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by grm** [comment]
I modified the required information here : 
- manifest has been updated on master : issue tracker has been defined : https://github.com/py-smart-gardena/hass-gardena-smart-system/commit/748c5c0862a9ae98a72c0212813cbb54b83fc15a
- owner has been updated on master : https://github.com/py-smart-gardena/hass-gardena-smart-system/commit/748c5c0862a9ae98a72c0212813cbb54b83fc15a
- brands has been added : https://github.com/home-assistant/brands/pull/1690
- wheels has been added : https://github.com/home-assistant/wheels-custom-integrations/pull/86

Can you relaunch the checks ?
Or do i have to wait for PR being merged ?

Thx,
Grm

**Comment by ludeeus** [comment]
Don't bother changing it again, I know that they are there.

**Pull request merged**
