### PR TITLE
Adds new integration [dgomes/rrd_recorder]

### PR DESCRIPTION
**Pull request by dgomes**
Adds new integration [dgomes/rrd_recorder] while still waiting for inclusion to Core

### CODE REVIEW

**Comment by dgomes** [comment]
This PR requires the user to install "rrdtool-dev" library, can't build the wheel without it... so I can't get this through HA...

**Comment by dgomes** [comment]
:(

**Comment by ludeeus** [comment]
When/if you get the needed wheels (and the other checks) sorted out, we can revisit this.
But until then, it does not make sense to distribute it.

**Comment by dgomes** [comment]
Users using core only are using it (they can simply install the C library dependency), I just haven't figured out the HA way of expressing that need.

I sure hope that it doesn't require that the Dockerfile needs to be changed

**Comment by ludeeus** [comment]
If it's only needed to build the wheel, and not during runtime, adding it to the list of apk's in the builder in the wheels repo for custom integrations should be enough.

**Comment by dgomes** [comment]
I did that, but it fails to validate because it doesn't have the C library in the validation container

https://github.com/home-assistant/wheels-custom-integrations/pull/193

**Comment by ludeeus** [comment]
Do a rebase, a lot has changed in that repo since you opened that PR

**Comment by dgomes** [comment]
It's always a catch22 ... I need to add the dependency to the GitHub workflows before it can actually run an validate the PR ...

**Comment by ludeeus** [comment]
I wonder if that job could/should be migrated to a container :thinking:

**Comment by dgomes** [comment]
I don't understand how other requirements don't face the same issue, or what am I doing wrong 😕

**Comment by ludeeus** [comment]
That would be nice, but currently, that's not an option

**Pull request closed without merging**
