### PR TITLE
Adds new integration [Verbalinsurection/next_rocket_launch]

### PR DESCRIPTION
**Pull request by Verbalinsurection**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by ludeeus** [comment]
This integration do I/O in the eventloop <https://github.com/Verbalinsurection/next_rocket_launch/blob/master/custom_components/next_rocket_launch/sensor.py#L98>.
That should be handled before it's added since that will cause issues with HA.

Also, does not this <https://www.home-assistant.io/integrations/launch_library/> provide the same info?

**Comment by Verbalinsurection** [comment]
Hello,

the launch_library provide informations for the next launch regardless of the type of rocket and launch. The goal here is to track the planning for interested rocket launch. It's like "When the next Ariane 5 will be launch ?", this can't be answered by launch_library.

I will check to fix the problem with the I/O in the eventloop, sorry for this, I don't have any issue with this since 1 month. I will fix this as soon as possible and thanks for this information.

**Comment by ludeeus** [comment]
> regardless of the type of rocket and launch.

Alright then 👍 

When you do I/O in the event loop, everything else is put on hold.
With the current beta of HA, it will also print a message about that.
<https://developers.home-assistant.io/docs/asyncio_working_with_async>

**Comment by Verbalinsurection** [comment]
Thanks for the link.
If the goal of this integration is not clear regards the launch_library, I will update the readme.md

**Comment by ludeeus** [comment]
It's probably fine, but 1 line more docs are always better than 1 line less ;)

**Comment by Verbalinsurection** [comment]
Hello :)
I have update the code. I add use of DataUpdateCoordinator so no I/O on eventloop (and no warning in console)
But one thing : 
- ICS from CALENDAR generate a warning on lhttps://github.com/Verbalinsurection/next_rocket_launch/blob/master/custom_components/next_rocket_launch/sensor.py#L81

`WARNING (MainThread) [asyncio] Executing <Task finished coro=<DataUpdateCoordinator._handle_refresh_interval() done, defined at /workspaces/Home-Assistant-core/homeassistant/helpers/update_coordinator.py:108> result=None created at /workspaces/Home-Assistant-core/homeassistant/core.py:314> took 1.967 seconds`

**Comment by ludeeus** [comment]
I don't know about that.
Do you want to hold off this until you solve it?

**Comment by Verbalinsurection** [comment]
No, it's ok for me to publish

**Pull request merged**
