### PR TITLE
Adds new integration [garbled1/balboa_homeassistan]

### PR DESCRIPTION
**Pull request by garbled1**
Before you submit a pull request, please make sure you have done the following:

- [X] You are submitting only 1 repository.
- [X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X] You have tested it with HACS by adding it as a custom repository.
- [X] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by garbled1** [comment]
Fixed json

**Comment by garbled1** [comment]
Fixed json for real this time.

**Comment by UbhiTS** [comment]
Please also give a sample configuration example. User does not know what library to import or config to add.

**Comment by garbled1** [comment]
There shouldn't be anything needed from the user, there is a config flow for this.  Once you add the component it just shows up in the integrations.  The library will auto install?

**Comment by ludeeus** [comment]
Fine to be added once the validation passes

**Comment by garbled1** [comment]
This is failing validation because balboa doesn't have a brand in the brands repository, which they are refusing to allow in, because balboa doesn't have a high quality square logo of any kind.  What am I supposed to do here?

**Comment by ludeeus** [comment]
You tried, that's what counts.
But it will hide other potential issues, so before we can merge this. please add the HACS action in your repo <https://hacs.xyz/docs/publish/action> with the SKIP_BRANDS_CHECK enabled, when it passes there, post a link to the check here.

**Comment by garbled1** [comment]
Haha, so of course I did that, and ran into https://github.com/hacs/integration/issues/1142 .

**Comment by garbled1** [comment]
Added action, which now passes cleanly.  Thank you for your assistance on this, was feeling chicken-egged.  :)

https://github.com/garbled1/balboa_homeassistan/actions/runs/100834210

**Pull request merged**
