### PR TITLE
Adds new integration [garbled1/homeassistant_ecowitt]

### PR DESCRIPTION
**Pull request by garbled1**
Before you submit a pull request, please make sure you have done the following:

- [X] You are submitting only 1 repository.
- [X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X] You have tested it with HACS by adding it as a custom repository.
- [X] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by garbled1** [comment]
Fixed json trailing comma

**Comment by UbhiTS** [comment]
Also, please fix the readme. New users, will probably need more information to help them setup this component. The instructions are a little unclear. Also the heading for the page.

**Comment by garbled1** [comment]
OK, fiddled the instructions, hopefully better now.

**Comment by garbled1** [comment]
OK, same as my balboa PR, I have attempted to add a logo, but the vendor does not have suitable logos available.  Per the instructions there, I have added the validation github action to my repo, which now passes cleanly.  Hopefully this satisfies requirements?

**Pull request merged**
