### PR TITLE
Adds new integration [Aohzan/hass-polar]

### PR DESCRIPTION
**Pull request by Aohzan**
hello,

to add the Polar integration https://github.com/Aohzan/hass-polar

brands MR in progress https://github.com/home-assistant/brands/pull/3950

thank you

### CODE REVIEW

**Comment by ludeeus** [comment]
Please do not open PRs before it's ready, thanks.

**Comment by Aohzan** [comment]
Is "The repository has no valid topics" stands for GitHub discussions ?

**Comment by Aohzan** [comment]
**Link to successful HACS action:**  https://github.com/Aohzan/hass-polar/actions/runs/3818072294
**Link to successful hassfest action (if integration):**  https://github.com/Aohzan/hass-polar/actions/runs/3818072290

**Comment by Aohzan** [comment]
@ludeeus should I open a new PR ?

**Comment by ludeeus** [comment]
please do

**Pull request closed without merging**
