### PR TITLE
Adds new integration [jampez77/Ryanair]

### PR DESCRIPTION
**Pull request by jampez77**
**Link to successful HACS action:** 
https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/actions/runs/4859046424
**Link to successful hassfest action (if integration):** 
https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/actions/runs/4859051568

### CODE REVIEW

**Comment by ludeeus** [comment]
CI fails.
integration is UK only and <https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/blob/main/hacs.json> country is missing

**Comment by jampez77** [comment]
> CI fails.
> integration is UK only and <https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/blob/main/hacs.json> country is missing

Ah, right you are. Updating now. Thanks

**Comment by jampez77** [comment]
> /recheck

Is this even a thing? I saw it in another PR 🤷

**Comment by tjorim** [comment]
Stop merging the master branch, it's only pushing your PR to the end of the list.

**Comment by jampez77** [comment]
> Stop merging the master branch, it's only pushing your PR to the end of the list.

Ah, ok. That explains a lot. I didn't know this was the case. Thanks for letting me know

**Comment by tjorim** [comment]
You just did it again ;)

**Comment by jampez77** [comment]
> You just did it again ;)

Yeah, it was because I've created another integration and PR so thought I needed to get the up to date branch before merging. I now assume that's not necessary.

**Comment by jampez77** [comment]
Closing this and going to start again as it's a confusing mess.

**Pull request closed without merging**
