### PR TITLE
Adds new plugin [RomRider/apexcharts-card]

### PR DESCRIPTION
**Pull request by RomRider**

### CODE REVIEW

**Comment by RomRider** [comment]
All good 👍

**Review by jurgenhaas — APPROVED** [review]

**Review by deepcoder — APPROVED** [review]
I am using this module with Home Assistant, and it will integrate better with insertion into HACS workflow. Please move this request forward.

**Review by RPI-PMK — APPROVED** [review]

**Review by markcocker — APPROVED** [review]
This card would be a great addition, and complementary to the existing graphing options in HA. I've been using it over the last week and the maintainer is very responsive.

**Review by Tommywelle — APPROVED** [review]

**Review by scooper1 — APPROVED** [review]

**Review by DavidFW1960 — APPROVED** [review]
Yes please add to HACS default

**Review by robertklep — APPROVED** [review]
Great addition to Lovelace, allows for very expressive and elaborate graphing 👍🏻

**Review by SeLLeRoNe — APPROVED** [review]
Very nice card, the next step for HA graphs :)

**Review by SeLLeRoNe — APPROVED** [review]

**Review by yuvalabou — APPROVED** [review]
LGTM

**Review by andrewdolphin — APPROVED** [review]

**Pull request merged**
