### PR TITLE
Adds new integration [sampsyo/hass-smartthinq]

### PR DESCRIPTION
**Pull request by sampsyo**
Adds [this LG SmartThinQ component](https://github.com/sampsyo/hass-smartthinq), as proposed in https://github.com/sampsyo/hass-smartthinq/pull/36#issuecomment-662885178.

### CODE REVIEW

**Comment by sampsyo** [comment]
I'm a little confused—the PR template just looked like a comment to me? Let me know if there's something I was supposed to fill out.

**Comment by ludeeus** [comment]
ignore that part

**Comment by javawizard** [comment]
👍 What else needs to happen before this can get merged in?

**Comment by ludeeus** [comment]
The failed checks need to pass.

- https://github.com/hacs/default/pull/550/checks?check_run_id=922650477#step:5:6
- https://github.com/hacs/default/pull/550/checks?check_run_id=922650521#step:5:7
- https://github.com/hacs/default/pull/550/checks?check_run_id=922650548#step:5:6
- https://github.com/hacs/default/pull/550/checks?check_run_id=922650532#step:5:7

**Pull request closed without merging**
