### PR TITLE
Adds new integration [gdgib/span]

### PR DESCRIPTION
**Pull request by gdgib**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/gdgib/span/releases/tag/v0.0.7
Link to successful HACS action (without the `ignore` key): https://github.com/gdgib/span/actions/runs/4653140311/jobs/8233748543
Link to successful hassfest action (if integration): https://github.com/gdgib/span/actions/runs/4653140311/jobs/8233748474

### CODE REVIEW

**Comment by gdgib** [comment]
Still holding out hope...

**Comment by tylas13** [comment]
Would be nice to have this loaded into the HACS repository, it is an essential integration for those that have a Span panel and want to get more functionality. 

Span engineers and marketing are in approval for this integration and are helping the devs of this integration as mentioned in this HA feed:  https://community.home-assistant.io/t/integration-with-span/370645/178

**Comment by tjorim** [comment]
If so, they should build an official integration and get it into HA core instead.

**Comment by gdgib** [comment]
I think there's some confusion about the word "essential" here, perhaps.  This is *NOT* required to operate or own the Span panel correctly.  It is however extremely useful to anyone owning a Span panel and using HA.

Span employees have specifically stated that they do not have plans to create such an HA core integration, as HA isn't a high enough priority for the company right now or in the foreseeable future (e.g. next few months to a year I would say).  They have also stated they're very glad to see us providing this solution, and are eager to support us as much as they can within their staffing & budget limits.

As a practical matter, that means they're looking at providing documentation for the APIs we're using, and they've been very slowly making life easier for us, but they're certainly not ready to contribute code or take ownership of the project.

They've made it clear this will have to be a community effort for the forseeable future.

**Comment by jeffkibuule** [comment]
Given that these panels are pretty expensive, I'm glad they aren't actively blocking us. Community efforts are good enough for me (far more responsive!).

**Comment by mbbush** [comment]
I work for span as a software developer, mostly working on things completely unrelated to the local API, but it's something I care about and choose to help out with as I have time (which lately has been not much, unfortunately). I use this integration myself on the span panel in my home, and intend to do what I can to improve it, as publicly as possible (opening [issues](https://github.com/galak/span-hacs/issues/11), debugging problems, and fixing bugs). 

Speaking on my own behalf (not my employer's) I'd love to see this merged into hacs default. I think it would be even better if Span could offer an official integration, and perhaps we will some day, but this is the best option that exists for now.

**Comment by sargonas** [comment]
Huge thanks to you @mbbush! As the head of devrel/community developer ecosystem, I know first hand how valuable it is for in-house engineers like you who support folks like us in your free time outside your day-to-day responsibilities. It is always an awesome thing and the fact there are folks like you there, and that Span let's you help support projects like this, is part of the reason why when I did all my research last month, I went with this panel!

**Comment by sargonas** [comment]
Hello HACS maintainers!

This is a petition to redirect this inclusion from the current repo of https://github.com/gdgib/span to https://github.com/Span-HA-Project/span.

The previous requester of this inclusion has been MIA for several months, during which time the Span developers have made several breaking changes to the platform that have required changes to the integration to maintain functionality. Those changes have been made, but PRs have been pending on this repo for many months without resolution, forcing folks to resort to running manual workarounds to run the unmerged code.

To resolve this, I have created a new GH organization and invited multiple maintainers to help curate it, so reduce any single point of failures, and propose this updated repo become the new primary source within HACS for the Span integration.

**Comment by ludeeus** [comment]
Redirects will not happen.
Only removals/addition (in separate PRs)

**Comment by tylas13** [comment]
> Redirects will not happen. Only removals/addition (in separate PRs)

What process would this look like - removal PR first and then Addition PR after?  Also, could both PR's happen inside the new repo [Span HA Project](https://github.com/Span-HA-Project/span) ?

**Comment by gdgib** [comment]
FWIW, I would support either way, and would be pleased to grant others maintener access to my fork. I will be catching up on this stuff over the weekend.

**Comment by sargonas** [comment]
In an ideal world, I would prefer we keep yours as the source of truth!

If you're around to help make that possible, then let's move forward with that, making yours collaborative!

**Comment by gdgib** [comment]
Yeah, that works for me.  @sargonas.  Just made you a collaborator, and I am definitely around to maintain this.

**Pull request merged**
