### PR TITLE
Adds new integration [rospogrigio/localtuya]

### PR DESCRIPTION
**Pull request by rospogrigio**

### CODE REVIEW

**Comment by KTibow** [comment]
I think you need to make a new release in order for this to work.

**Comment by rospogrigio** [comment]
> I think you need to make a new release in order for this to work.

What do you mean? A new PR?

**Comment by KTibow** [comment]
One of these: https://github.com/rospogrigio/localtuya-homeassistant/releases

**Comment by KTibow** [comment]
I think it's failing because the repo's name and the custom component's name conflict, `localtuya` != `localtuya-homeassistant`.

**Comment by ludeeus** [comment]
Repo name does not matter, <https://github.com/rospogrigio/localtuya-homeassistant/blob/master/hacs.json#L2> the content_in_root key here, might be the issue, remove it.

Also, remove this from the readme " / Hass.io add-on", 1) Hass.io is an old term 2) it's not an add-on

**Comment by rospogrigio** [comment]
So now all the checks are passing (apart from the optional fork)... is there anything else I am supposed to do?
Will the Integration be available immediately or a new release of HACS or HA must be released?
Thank you for the support

**Comment by KTibow** [comment]
As soon as the PR is merged, it'll be added. All HACS installations check for new repositories about every 30 minutes, and it'll show up as a "New repository".

**Review by postlund — APPROVED** [review]

**Comment by rospogrigio** [comment]
Dear @ludeeus  @KTibow , may I kindly ask you when we can expect this PR to be merged? I don't mean to seem pushy in any way, and I know you are probably busy setting up the Conference but we are avoiding publishing new releases of our integration to avoid messing up things with this PR, so it would be useful to know the timing, if any.
Thank you for all your work! 😄

**Pull request merged**
