### PR TITLE
remove repository "r-renato/hass-xiaomi-mi-flora-and-flower-care"

### PR DESCRIPTION
**Pull request by r-renato**
remove repository "r-renato/hass-xiaomi-mi-flora-and-flower-care"

### CODE REVIEW

**Comment by r-renato** [comment]
Please, can you approve this merge?

**Comment by ludeeus** [comment]
What are you doing?
Asking to be removed, and when I do that you don't want to be removed?

**Comment by r-renato** [comment]
Sorry, I wanted to restore the initial state and put my repository in the integration components.

**Comment by ludeeus** [comment]
Then you need to make a new PR to add it in the correct category and mention there that it should be removed from the blacklist.

**Comment by r-renato** [comment]
Ok, thank you!

**Pull request closed without merging**
