### PR TITLE
Adds new integration [sillyfrog/Automate-Pulse-v2]

### PR DESCRIPTION
**Pull request by sillyfrog**
Re-requesting the addition of this to default HACS as adding to Home Assistant core has been effectively rejected. I need to merge my code with some other code written by someone else that has not been active for some time, for hardware I don't own (this is a PR I have been working on for nearly a year, it was accepted, then someone else jumped in and changed everything - again - it's very frustrating - along with many things they want in the code that are not documented that are drip fed to me every few days). See [here](https://github.com/home-assistant/core/pull/53704) for full details. I have closed off my other related PR's in HA as well.

Thanks!

### CODE REVIEW

**Review by jbouwh — APPROVED** [review]
LGTM

**Comment by aex351** [comment]
Quick glance, looks good. 

For the `core` I can imagine why they would like to have this integrated within `acmeda` integration. However, I feel they should have accepted this as-is, because Automate Shades is a separate company, even though its parent company is Rollease Acmeda. So a user that bought Automate Shades will look for an integration with a similar name, they probably won't look for the Rollease Acmeda integration.

I feel it is a bit like Zigbee. If you buy some Ikea lights, you want the Ikea integration. Sure you probably can also make use of the Philips Hue integration or vice versa or even some generic Zigbee integration. Doesn't mean you all need to integrate them in to one.

**Review by aex351 — APPROVED** [review]

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

**Comment by sillyfrog** [comment]
Confirming I have put in a PR at HA Brands to move it from `core_integrations` to `custom_integrations` (#2749)

**Pull request merged**
