### PR TITLE
Adds new integration [JeffSteinbok/hass-dreo]

### PR DESCRIPTION
**Pull request by JeffSteinbok**
Adding Dreo integration from https://github.com/JeffSteinbok/hass-dreo

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/JeffSteinbok/hass-dreo/releases/tag/v0.3.0
Link to successful HACS action (without the `ignore` key): https://github.com/JeffSteinbok/hass-dreo/actions/runs/5603012542
Link to successful hassfest action (if integration): https://github.com/JeffSteinbok/hass-dreo/actions/runs/5603012544

### CODE REVIEW

**Comment by JeffSteinbok** [comment]
@ludeeus - Am I missing a step here for someone from HACS to review/approve?

**Comment by JeffSteinbok** [comment]
Thanks @ludeeus  - Fixed casing issue.

**Review by JeffSteinbok — COMMENTED** [review]
Look good

**Comment by JeffSteinbok** [comment]
@ludeeus  - I'm sorry, I'm confused - what do I need to do next to get this in?

**Comment by tjorim** [comment]
Nothing, your integration should be next on the list. If he has time he will probably merge some PRs this weekend.

**Pull request merged**
