### PR TITLE
Adds new integration [amitfin/daily_schedule]

### PR DESCRIPTION
**Pull request by amitfin**
**Link to successful HACS action:**  https://github.com/amitfin/daily_schedule/runs/7808089153
**Link to successful hassfest action (if integration):**  https://github.com/amitfin/daily_schedule/runs/7808089153

### CODE REVIEW

**Comment by amitfin** [comment]
HACS and hassfest actions are defined [here](https://github.com/amitfin/daily_schedule/blob/master/.github/workflows/cron.yaml).

**Comment by ludeeus** [comment]
Have you seen <https://next.home-assistant.io/integrations/schedule/>?
image

**Comment by amitfin** [comment]
@ludeeus, yes I'm aware of the new schedule integration. 
Actually, this new core integration is based on [my work](https://github.com/home-assistant/core/pull/41385) :-)
However, the core team decided that they will go with a weekly schedule (only). This is not so usable for daily routines as the time periods need to be set for every day separately.
So, I'm adding here (HACS) the Daily Schedule for people who are interested in scheduling daily routines.
Does it make sense?

**Comment by ludeeus** [comment]
I dont see a difference, but Im not the target 🤷‍♂️

**Pull request merged**
