### PR TITLE
Adds new integration [exxamalte/home-assistant-custom-components-nsw-rural-fire-service-fire-danger]

### PR DESCRIPTION
**Pull request by exxamalte**

### CODE REVIEW

**Comment by exxamalte** [comment]
Sorry, just realised that this is still pending https://github.com/home-assistant/wheels-custom-integrations/pull/196 being merged.

**Review by DCSBL — APPROVED** [review]

**Review by jugla — APPROVED** [review]

**Review by msekoranja — APPROVED** [review]

**Pull request merged**
