### PR TITLE
Adds new integration [olibos/HomeAssistant-RecycleApp]

### PR DESCRIPTION
**Pull request by olibos**
Add https://github.com/olibos/HomeAssistant-RecycleApp to the list of integrations

**Link to successful HACS action:** https://github.com/olibos/HomeAssistant-RecycleApp/actions/runs/3411726129/jobs/5676298332
**Link to successful hassfest action:** https://github.com/olibos/HomeAssistant-RecycleApp/actions/runs/3411726130/jobs/5676298641

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
https://github.com/olibos/HomeAssistant-RecycleApp/blob/main/hacs.json missing country

**Comment by olibos** [comment]
Thank you for your feedback @ludeeus 🙂
In the [documentation](https://hacs.xyz/docs/publish/start/#hacsjson), that property was noted as not required.
Is it outdated?
Let me know if I've miss something else 😉

**Comment by ludeeus** [comment]
It's optional meaning most don't needed, you repo only are useful for users in a specific country and then it should be set.

**Comment by olibos** [comment]
You're right, I've updated the code and make a new release with the country code: 
https://github.com/olibos/HomeAssistant-RecycleApp/blob/v1.2.0/hacs.json

**Pull request merged**
