### PR TITLE
Adds new integration [heyajohnny/cryptoinfo]

### PR DESCRIPTION
**Pull request by heyajohnny**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by heyajohnny** [comment]
It's failing on this check:
hacs.repository.integration.heyajohnny.cryptoinfo - Integration not added to https://github.com/home-assistant/brands

Why is it necessary to add my integration to https://github.com/home-assistant/brands ?

**Comment by ludeeus** [comment]
To provide the best possible experience for the user.

**Comment by heyajohnny** [comment]
I've added my icons for this integration to https://github.com/home-assistant/brands and it's already merged.
But I don't know how to rerun the 'Validate with HACS / Validate (pull_request)' check. 
:(

**Comment by heyajohnny** [comment]
It's working now, Thnx 👍

**Pull request merged**
