### PR TITLE
Adds new integration [custom-components/remote_homeassistant]

### PR DESCRIPTION
**Pull request by lukas-hetzenecker**
Plugin remote_homeassistant has been migrated
from lukas-hetzenecker/home-assistant-remote
to custom-components/remote_homeassistant

### CODE REVIEW

**Comment by postlund** [comment]
@lukas-hetzenecker There are som failing checks, do you have time to look into those?

**Comment by lukas-hetzenecker** [comment]
@postlund sure, will do

**Comment by lukas-hetzenecker** [comment]
@postlund that will be a bit more complicated :sweat: 
❌ The repository is missing topics (more-info: https://hacs.xyz/docs/publish/include#check-repository )
With the migration, I seem to have lost the ability to change the project settings

**Comment by postlund** [comment]
@ludeeus We seem to be stuck in a limbo here as @lukas-hetzenecker is lacking permissions to fix errors in the checks. I'm also supposed to take ownership of this project, so I guess I need to be added to the organization and given permission to the repo?

**Comment by ludeeus** [comment]
Was corrected 3 days ago, there is no higher:
image

**Comment by postlund** [comment]
@ludeeus Ah, great, thanks! Can @lukas-hetzenecker add me as an admin or does that require super user power?

**Comment by ludeeus** [comment]
There is nothing higher than admin, he can do it if he feels you should have that.

**Comment by postlund** [comment]
Top notch, thanks again! 👍

**Comment by lukas-hetzenecker** [comment]
@postlund Yep, everything should be setup correctly now. Could fix the project settings, and added you as admin.

The tests should now also run successfully ( @ludeeus  - please note that only the location of the repo changed, it's already included in HACS)

**Comment by postlund** [comment]
@lukas-hetzenecker Yeah, I can access settings of the project now so it seems to work. A bit peculiar that I haven't received any kind of notification regarding this however. But maybe that's how it's supposed to be.

**Comment by lukas-hetzenecker** [comment]
@ludeeus it should be possible to merge this now, test errors should be resolved (just can't trigger a recheck myself)

**Comment by makuser** [comment]
What exactly seems to be blocking this?

**Review by ludeeus — CHANGES_REQUESTED** [review]
The `manifest.json` file has a `homeassistant` key, and it's missing a `version` key

**Comment by lukas-hetzenecker** [comment]
@ludeeus thanks for the hint what the issue was, `version` key got added.
Will publish a new release, as soon as this is merged

**Comment by tmcarr** [comment]
@lukas-hetzenecker I think someone needs to do a release here. Can someone trigger one?

**Pull request merged**
