### PR TITLE
Adds new integration [osk2/panasonic_smart_app]

### PR DESCRIPTION
**Pull request by osk2**
New integration for Panasonic Smart App

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
README should include why this exist, and the differences between this and integration by @PhantasWeng it is based on <https://github.com/PhantasWeng/panasonic_smart_app>

**Comment by PhantasWeng** [comment]
@ludeeus Thanks for mentioned.

@osk2 fork my repository and optimized.

I'm glad to see this can be in default but please mention me in your README and add my GitHub link as references.

**Comment by osk2** [comment]
Sure thing! will update README asap.

**Comment by osk2** [comment]
@ludeeus README is updated 👏🏼

**Pull request merged**
