### PR TITLE
Adds new integration [dimagoltsman/ha-proof-dashcam-integration]

### PR DESCRIPTION
**Pull request by dimagoltsman**

### CODE REVIEW

**Comment by ludeeus** [comment]
Add https://github.com/hacs/action to your repo and you can verify each commit/PR

Also <https://hacs.xyz/docs/publish/include#re-run-checks>

**Comment by dimagoltsman** [comment]
@dgomes hey, can u maybe help? i dont understand the error and how is it related to my integration?

```
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
  WARNING: The script wheel is installed in '/home/runner/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by dgomes** [comment]
Check the action logs:
```

  Error:  ::error:: No hacs.json file in the root of the repository.
386
  Error: HACS load check
```

**Comment by dimagoltsman** [comment]
@dgomes its there, i see another error

**Comment by dimagoltsman** [comment]
https://github.com/dimagoltsman/ha-proof-dashcam-integration/blob/main/hacs.json

its in the root...

**Comment by dgomes** [comment]
@ludeeus could you please help out here ?

**Review by ludeeus — CHANGES_REQUESTED** [review]
https://github.com/dimagoltsman/ha-proof-dashcam-integration/tree/0.1.1
Missing file.

**Comment by dimagoltsman** [comment]
ooohh.... didnt know it looks for the tag... thanx!

**Comment by dimagoltsman** [comment]
@dgomes  

done, thanx!

**Review by ludeeus — CHANGES_REQUESTED** [review]
This device is only available in a single country, add the country key to hacs.json

**Review by ludeeus — APPROVED** [review]

**Pull request merged**
