### PR TITLE
Adds new integration [wills106/homeassistant-solax-modbus]

### PR DESCRIPTION
**Pull request by wills106**
**Link to successful HACS action:**  
**Link to successful hassfest action (if integration):**

### CODE REVIEW

**Comment by wills106** [comment]
Just realised I had spelt the repository for my SolaX Integration wrong "wills106/homsassistant-solax-modbus", it should be "wills106/homeassistant-solax-modbus" I corrrected the repository name and also updated the integration file on here.

Should I have done it as two seperate PR's?

**Comment by wills106** [comment]
Am I best closing this PR down and doing two separate ones?

**Comment by ludeeus** [comment]
Yes.
1 item on each PR.

**Pull request closed without merging**
