### PR TITLE
Remove MatthewFlamm/nwsradar

### PR DESCRIPTION
**Pull request by MatthewFlamm**
NWS removed the server for radar images breaking this integration.

### CODE REVIEW

**Comment by UbhiTS** [comment]
This change should not be causing conflicts. Maybe I don't understand the process. But approved for now.

**Comment by MatthewFlamm** [comment]
Looks like the checks expect there to be a new repo added.  I'm also unsure of what should be done.

**Comment by KTibow** [comment]
Usually people flag a repo instead of creating a PR to remove it.

**Comment by MatthewFlamm** [comment]
Why should it still be in the default list in this case?

**Comment by KTibow** [comment]
What do you mean? Did you flag it already?

**Comment by MatthewFlamm** [comment]
I now see the documentation here, but there are a few problems.  I currently have no means to run the `make` command locally for a few weeks.  The other is the warning: 

> If you as a maintainer delete/remove a repository that is added to HACS as a default repository, all your default repositories will be removed from HACS and you will not be able to add any more in the future.

This is very harsh.  Why will I be barred from having future default repositories since this one is broken due to NWS deprecation?

**Comment by ludeeus** [comment]
That's in regards to removing/deleting a repo from GitHub, what you do here is fine 👍

**Comment by MatthewFlamm** [comment]
> That's in regards to removing/deleting a repo from GitHub,

Phew... Could be clearer, will take a look at how to clarify.  If it makes sense, I can create a PR in the same format as:

https://github.com/hacs/default/commit/c8920037932cf90511c3fce8d40f5e90caa03a44

**Comment by MatthewFlamm** [comment]
Apparently using `make remove` also does not fix the CI checks.

**Comment by ludeeus** [comment]
The CI here is designed for new additions, ignore it

**Review by ludeeus — APPROVED** [review]

**Comment by MatthewFlamm** [comment]
Thanks!

**Comment by FutureTense** [comment]
@MatthewFlamm sorry to bother you, but what did you do when you ran make remove?  I’m trying to run this ans am getting syntax errors.

**Comment by MatthewFlamm** [comment]
@FutureTense I followed the directions above.  I didn't have a computer, but used Termux on Android.

My guess would be a python version issue, but hard to say without seeing the errors.

**Pull request merged**
