### PR TITLE
Adds new integration [muchasuerte/ha-besmart]

### PR DESCRIPTION
**Pull request by muchasuerte**

### CODE REVIEW

**Comment by KTibow** [comment]
Mind adding these topics:
- home-assistant
- homeassistant
- python
- python3
- thermostat
to your repo?

**Comment by muchasuerte** [comment]
Various improvements, pull request merged & topics updated

**Comment by muchasuerte** [comment]
hacs.json updated!

**Comment by muchasuerte** [comment]
https://github.com/muchasuerte/ha-besmart/actions/runs/322742794 Action Validation And Formatting, completed.

**Pull request closed without merging**
