### PR TITLE
Adds new integration [msekoranja/emsc-hacs-repository]

### PR DESCRIPTION
**Pull request by msekoranja**

### CODE REVIEW

**Review by DCSBL — APPROVED** [review]

**Review by jugla — APPROVED** [review]

**Review by jellespijker — APPROVED** [review]

**Comment by msekoranja** [comment]
Is it common that the review process takes so long (more than a month now)?

**Comment by jellespijker** [comment]
To quote @ludeeus on the discord channel when I asked the same question.

> Usually < 1 week But nothing will be reviewed by me (i bypass the 3 person rule) untill the next version of hacs is released

I think we have to be patient for a while. That being said, I hope you will help out as well when you got write access, by reviewing other PRs

**Comment by DCSBL** [comment]
To quote @ludeeus:

> Usually < 1 week
> But nothing will be reviewed by me (i bypass the 3 person rule) untill the next version of hacs is released

**Comment by jugla** [comment]
A new Hacs version has been released today. I've not seen HACS default updated ...
Perhaps it is linked with all protections put inside HomeAssistant in new version ...

**Pull request merged**
