### PR TITLE
Adds new integration [lizardsystems/hass-taipit]

### PR DESCRIPTION
**Pull request by vzagorovskiy**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/lizardsystems/hass-taipit/releases/tag/v1.0.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/lizardsystems/hass-taipit/actions/runs/4367276327>
Link to successful hassfest action (if integration): <https://github.com/lizardsystems/hass-taipit/actions/runs/4367276334>

### CODE REVIEW

**Comment by ludeeus** [comment]
PR is not editable.

**Comment by vzagorovskiy** [comment]
> PR is not editable.

Sorry what did you mean

**Comment by elchininet** [comment]
Hi @vzagorovskiy,

If you disable this checkbox, the pull request cannot be edited by maintainers.

image

**Comment by vzagorovskiy** [comment]
@elchininet Thank you!

**Pull request closed without merging**
