### PR TITLE
Adds new integration [tikismoke/home-assistant-nespressoble]

### PR DESCRIPTION
**Pull request by tikismoke**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by tikismoke** [comment]
Could somenone tell me what's wrong with my PR?

**Comment by ludeeus** [comment]
@tikismoke You missed one of the tasks, that made some of the CI not start.
image

**Comment by tikismoke** [comment]
Hi sorry this is my first one and do not know all rules for the moment.

Will do better next time ;)

Le 25 mai 2020 19:52:55 GMT+02:00, "Joakim Sørensen" <notifications@github.com> a écrit :
>@tikismoke You missed one of the tasks, that made some of the CI not
>start.
>image
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/hacs/default/pull/384#issuecomment-633667862

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

Attention nous avons changer de domaine, utilisez poudot.fr à la place de tikijs.dyndns.org

**Comment by tikismoke** [comment]
https://github.com/home-assistant/wheels-custom-integrations/pull/77

**Comment by tikismoke** [comment]
https://github.com/home-assistant/brands/pull/1671

**Comment by tikismoke** [comment]
https://github.com/home-assistant/brands/pull/1671

**Comment by tikismoke** [comment]
YES :)
finally get to pass all tests and PR all over other repo :)

So happy.

**Pull request merged**
