### PR TITLE
Adds new integration [youdroid/home-assistant-sickchill]

### PR DESCRIPTION
**Pull request by youdroid**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by youdroid** [comment]
Can anyone tell me why test fail, I did'nt understand ?
Thank you

**Comment by ludeeus** [comment]
<https://github.com/hacs/default/pull/419/checks?check_run_id=658828350#step:6:14>
<https://hacs.xyz/docs/publish/integration#additional-requirements-for-integrations>

**Comment by youdroid** [comment]
Yes I checked logs but I don't understand what is this error :

>  Integration not added to https://github.com/home-assistant/brands

**Comment by msp1974** [comment]
Seems a requirement to pass the tests now needs a logo adding to homeassistant brands. The error log is telling you that it has not been added. See the second link ludeeus posted and get a logo and do a PR to add to the homeassistant brands repo. Hope that helps.

**Comment by youdroid** [comment]
Ok, thank you for your advice. 
I understood the same thing as you, but  I wanted a confirmation.
But it 's a little strange, for my previous PR I didn't need to do this, and I passed the test.

**Comment by ludeeus** [comment]
New requirements are added when needed, or when I can, to give the user the best possible experience

**Comment by youdroid** [comment]
Ok,I did not know, I just put the sickchill pictures to brands repo. It's ok now ! 
Thx

**Pull request merged**
