### PR TITLE
Adds new integration [stuart-c/homeassistant-switchbot]

### PR DESCRIPTION
**Pull request by stuart-c**
New integration for SwitchBot which uses the cloud rather than bluetooth.

### CODE REVIEW

**Review by DCSBL — APPROVED** [review]

**Review by jellespijker — DISMISSED** [review]

**Review by ludeeus — CHANGES_REQUESTED** [review]
https://github.com/hacs/default/pull/783/checks?check_run_id=1857718235#step:2:316

**Comment by stuart-c** [comment]
That is now passing @ludeeus

**Review by ludeeus — CHANGES_REQUESTED** [review]
https://github.com/stuart-c/homeassistant-switchbot/blob/main/info.md
No information given

**Review by dreed47 — APPROVED** [review]

**Comment by ludeeus** [comment]
Closing as stale

**Pull request closed without merging**
