### PR TITLE
Adds new integration [r-renato/ha-climacell-weather]

### PR DESCRIPTION
**Pull request by r-renato**
Add new integration r-renato/ha-climacell-weather

Before you submit a pull request, please make sure you have done the following:

- [X] You are submitting only 1 repository.
- [X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X] You have tested it with HACS by adding it as a custom repository.
- [X] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by r-renato** [comment]
please, can you review this pull request and approve? thx, Renato

**Comment by Verbalinsurection** [comment]
Code looks ok for me.
Integration work but one error log :

> Logger: homeassistant.helpers.service
> Source: helpers/service.py:258
> First occurred: 4:29:20 (1 occurrences)
> Last logged: 4:29:20
> 
> Unable to find services.yaml for the climacell integration

and, but I may have looked badly, one thing missing : the weather state to use with weather card directly like this : 

(weather.house)
> temperature: 7.8
> humidity: 93
> ozone: 384.9
> pressure: 1004.8
> wind_bearing: 234
> wind_speed: 21.8
> visibility: 16.093
> attribution: Powered by Dark Sky
> forecast:
>   - datetime: '2020-04-29T22:00:00+00:00'
>     temperature: 12.6
>     templow: 7
>     precipitation: 6
>     wind_speed: 28.45
>     wind_bearing: 224
>     condition: rainy
>   - datetime: '2020-04-30T22:00:00+00:00'
>     temperature: 13.9
>     templow: 6.2
>     precipitation: 3.2
>     wind_speed: 19.67
>     wind_bearing: 244
>     condition: rainy
>   - datetime: '2020-05-01T22:00:00+00:00'
>     temperature: 15
>     templow: 7.1
>     precipitation: 1.8
>     wind_speed: 13.39
>     wind_bearing: 274
>     condition: rainy
>   - datetime: '2020-05-02T22:00:00+00:00'
> ...

**Comment by r-renato** [comment]
Thanks for your review. I have added the file services.yaml and improved the component documentation. Now the README include an example of the exposed sensor data.
Renato

**Comment by Verbalinsurection** [comment]
Two last things :
- You have a API KEY in comment https://github.com/r-renato/ha-climacell-weather/blob/c642a4bce106dd8b84194047b8bf02df4e2bcee8/custom_components/climacell/__init__.py#L35
- This line generate a warning in log : https://github.com/r-renato/ha-climacell-weather/blob/c642a4bce106dd8b84194047b8bf02df4e2bcee8/custom_components/climacell/__init__.py#L116

> /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.climacell.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

**Comment by ludeeus** [comment]
@r-renato Do not request reviews like that, someone will have a look if/when they got time.

@Verbalinsurection We do not generally do a review for custom things, if you like it and want to use it yourself, that is great but it's not needed to test things for a review here, unless you see things that will harm the users HA installation, you can reach me @ discord if something is not clear :)
https://discord.gg/apgchf8

We should only check that the repo structure is ok, and the rules to add a repository are followed (the bot also do that, but I do not trust that 100% yet.)

**Comment by Verbalinsurection** [comment]
OK, thanks for this precision @ludeeus

**Comment by r-renato** [comment]
#ludeeus ok, i also agree. In any case thanks @Verbalinsurection

**Comment by ludeeus** [comment]
Nice nice 🎉
This is the first one that was merged by someone other than me 🎉

**Pull request merged**
