### PR TITLE
Adds new integration [epaulsen/energytariff]

### PR DESCRIPTION
**Pull request by epaulsen**
**Link to successful HACS action:**  
https://github.com/epaulsen/energytariff/actions/runs/4086940880/jobs/7046845228

**Link to successful hassfest action (if integration):**  https://github.com/epaulsen/energytariff/actions/runs/4086940880/jobs/7046845345

### CODE REVIEW

**Comment by ludeeus** [comment]
<https://github.com/epaulsen/energytariff/blob/main/custom_components/energytariff/manifest.json> this fails hassfest.

**Comment by epaulsen** [comment]
@ludeeus I am sorry for the trouble, but can you provide any insights into how this fails hassfest?  
I do believe that I followed the instructions for setting up github actions, and everything looks green from the action board?

image

**Comment by epaulsen** [comment]
@ludeeus : Updated to v3 of actions and fixed errors, now passing hassfest validation again.  
Sorry about that 😄 

Successfull hassfest run: https://github.com/epaulsen/energytariff/actions/runs/4279576830/jobs/7450428426

**Comment by ludeeus** [comment]
<https://github.com/epaulsen/energytariff/blob/main/.devcontainer/devcontainer.json#L3>
You should move away from that ([reason](https://github.com/ludeeus/container#deprecated)).
Example for an alternative:
- [`.devcontainer.json`](https://github.com/ludeeus/integration_blueprint/blob/main/.devcontainer.json)
- [scripts dir instead of `container` CLI](https://github.com/ludeeus/integration_blueprint/tree/main/scripts)

**Pull request merged**
