### PR TITLE
Adds new integration [al-one/hass-miio-yeelink]

### PR DESCRIPTION
**Pull request by al-one**

### CODE REVIEW

**Review by DCSBL — APPROVED** [review]

**Review by ludeeus — CHANGES_REQUESTED** [review]
https://github.com/hacs/default/pull/771/checks?check_run_id=1857490276#step:2:377

**Comment by al-one** [comment]
@ludeeus What can I do ?
https://github.com/hacs/default/pull/771/checks?check_run_id=1870526819#step:2:418

**Pull request merged**
