### PR TITLE
Adds new integration [robinostlund/homeassistant-volkswagencarnet]

### PR DESCRIPTION
**Pull request by robinostlund**
Before you submit a pull request, please make sure you have done the following:

- [X] You are submitting only 1 repository.
- [X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X] You have tested it with HACS by adding it as a custom repository.
- [X] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by isabellaalstrom** [comment]
Wheels in progress:
https://github.com/home-assistant/wheels-custom-integrations/pull/97

**Comment by isabellaalstrom** [comment]
Brands: https://github.com/home-assistant/brands/pull/1710

**Comment by isabellaalstrom** [comment]
Everything should be in progress to be fixed now!

**Comment by robinostlund** [comment]
Ready for review and merge :)

**Pull request merged**
