### PR TITLE
Adds new integration [scottyphillips/echonetlite_homeassistant]

### PR DESCRIPTION
**Pull request by scottyphillips**

### CODE REVIEW

**Comment by DurgNomis-drol** [comment]
Is there a particular reason why you have not added any brand images to [home-assistant/brands](https://github.com/home-assistant/brands)?

**Comment by scottyphillips** [comment]
> Is there a particular reason why you have not added any brand images to [home-assistant/brands](https://github.com/home-assistant/brands)?

Any particular reason you didn’t check the PRs over at home-assistant/brands? 🤷🏼‍♂️

**Comment by DurgNomis-drol** [comment]
I was asking a genuine question. It was to help you get you integration added faster. But thanks for assuming that I had ill intend.

**Comment by scottyphillips** [comment]
> I was asking a genuine question. It was to help you get you integration added faster. But thanks for assuming that I had ill intend.

Sorry. I am actually trying to update an existing HACS repo. And yes I have put in a PR for the logos which i am waiting on. Your question was extremely direct and the way you framed it did not strike me as immediately helpful rather it came across to me like you were lecturing me.. just as a suggestion, next time start a conversation with “Hello” and you will less likely cause misunderstanding in tone. Apologies for the misunderstanding however..

**Comment by scottyphillips** [comment]
Hello there HACS team - just wondering is there anything else that I need to action to get this PR approved?

**Review by ludeeus — CHANGES_REQUESTED** [review]
This PR does nothing

**Comment by scottyphillips** [comment]
Closing because it looks like for whatever reason that my requested change (to rename a repo) has already been committed previously..

**Pull request closed without merging**
