### PR TITLE
Adds new integration [shutupflanders/sensor.moneydashboard]

### PR DESCRIPTION
**Pull request by shutupflanders**
Before you submit a pull request, please make sure you have the following:

- [X] You are submitting only 1 repository.
- [X] You repository is compliant with https://hacs.xyz/docs/publish/start
- [X] You have tested it with HACS by adding it as a custom repository

### CODE REVIEW

**Comment by ludeeus** [comment]
How much is left before I can add it?
Currently, it's on hold until these tasks are complete.
image

**Comment by shutupflanders** [comment]
Ah that's all done.

Didn't know you could tick it?

**Comment by ludeeus** [comment]
You can (and should) to indicate that you are done with your part of the PR (they are still not checked BTW)

**Comment by shutupflanders** [comment]
Done @ludeeus - apologies

**Pull request merged**
