### PR TITLE
Adds new integration [dphae/bsh]

### PR DESCRIPTION
**Pull request by DarkPark**

### CODE REVIEW

**Comment by DarkPark** [comment]
CI failed with the message `bsh is not added to https://github.com/home-assistant/brands`.
But this integration is local to my city (the brand is almost noname) and I don't think Home Assistant team will add it theirs brands repo.

**Comment by ludeeus** [comment]
They will

**Comment by DarkPark** [comment]
@ludeeus they really have :)
But I can't see a way to restart failed checks.

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/publish/include#re-run-checks

**Comment by DarkPark** [comment]
@ludeeus thank you for your previous help
is there anything I need to fix to move this PR?

**Pull request merged**
