### PR TITLE
Adds new plugin [elax46/custom-brand-icons]

### PR DESCRIPTION
**Pull request by elax46**
Custom brand icons for Home Assistant

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass

**Comment by elax46** [comment]
I can't understand what the problem is maybe because I uploaded the images to cloudinary and not in the plugin repo?

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/publish/include#lint-sorted

**Pull request merged**
