### PR TITLE
Adds new integration [ThermIQ/thermiq_mqtt-ha]

### PR DESCRIPTION
**Pull request by ThermIQ**
Please find an integration for controlling Thermia / Danfoss heatpumps via ThermIQ-MQTT Hardware interface

Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [ ] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list is still alphabetical after my change.

### CODE REVIEW

**Comment by ThermIQ** [comment]
Not shure if I should do something more to get this PR approved. Please advise...

**Comment by ludeeus** [comment]
You have 4 failed checks, those needs to pass before it can be merged

**Comment by ThermIQ** [comment]
I've added a new PR as the failing checks were due to outdated automatic checks. New one passes OK.

**Pull request closed without merging**
