### PR TITLE
Adds new integration [AlexxIT/GyverLamp]

### PR DESCRIPTION
**Pull request by AlexxIT**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
This needs the country key set in hacs.json https://hacs.xyz/docs/publish/start#hacsjson

**Comment by gjohansson-ST** [comment]
hacs.json is not part of the published version which I believe is a requirement for last check to run through

**Comment by ludeeus** [comment]
Closing as stale

**Pull request closed without merging**
