### PR TITLE
Adds new integration [mill1000/midea-ac-py]

### PR DESCRIPTION
**Pull request by mill1000**
## Justification
The original project (mac-zhou/midea-ac-py) hasn't seen any development in the prior year. Issues and pull requests have been left open and unaddressed. I've taken it upon myself to maintain a fork active and have been supporting users when possible.

I'm unsure of the etiquette around removing existing entries in the list. If the originals should be kept I will gladly change the commit.

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/mill1000/midea-ac-py/releases/tag/2023.9.5>
Link to successful HACS action (without the `ignore` key): <https://github.com/mill1000/midea-ac-py/actions/runs/6229915575>
Link to successful hassfest action (if integration): <https://github.com/mill1000/midea-ac-py/actions/runs/6229915576>

### CODE REVIEW

**Comment by ludeeus** [comment]
You should not remove in this PR.
Removing have a different way.

**Comment by mill1000** [comment]
Understood.  I've restored the original repos.

**Comment by mill1000** [comment]
I've found the documentation for removal here: https://hacs.xyz/docs/publish/remove

Should I create a PR or two?) or is it better to create an issue to request removal in this repo?

**Comment by ludeeus** [comment]
https://github.com/hacs/integration/issues/new?assignees=ludeeus&labels=flag&projects=&template=removal.yml

**Comment by mill1000** [comment]
Updates links to latest release and action runs.

**Comment by tjorim** [comment]
That's not needed if the initial release and action run was okay. Any change you make to the PR will push it to the back of the queue.

**Comment by mill1000** [comment]
Good to know. Thanks!

**Pull request merged**
