### PR TITLE
Adds new integration [sca075/valetudo_vacuum_camera]

### PR DESCRIPTION
**Pull request by sca075**
Added sca075/valetudo_vacuum_camera to integrations

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/sca075/valetudo_vacuum_camera/releases>
Link to successful HACS action (without the `ignore` key): <https://github.com/sca075/valetudo_vacuum_camera/actions/runs/7924050289/job/21634944039>
Link to successful hassfest action (if integration): <https://github.com/sca075/valetudo_vacuum_camera/actions/runs/7924034812/job/21634904522>

### CODE REVIEW

**Comment by tjorim** [comment]
List is not correctly sorted.

**Comment by tjorim** [comment]
Somehow it looks worse now?

**Comment by sca075** [comment]
> Somehow it looks worse now?

I'm a little bit confused 🫤 it is now sorted with the sort function in Python.. I can also remove this commit if this is creating problems.

Can you please explain what do you mean with not sorted??

**Comment by tjorim** [comment]
It's sorted correctly now but the indentation of the whole file is changed according to GitHub.

**Comment by sca075** [comment]
> List is not correctly sorted.

re-committed in sorted way.

> It's sorted correctly now but the indentation of the whole file is changed according to GitHub.

okay I will change the intention to original just to be clear I'm using this..

```
sorted_list = sorted(my_list)

for item in sorted_list:
    print(f'"{item}",')

is_sorted = all(sorted_list[i] <= sorted_list[i+1] for i in range(len(sorted_list)-1))

print("Is the list sorted?", is_sorted)
```

**Comment by sca075** [comment]
> > List is not correctly sorted.
> 
> re-committed in sorted way.
> 
> > It's sorted correctly now but the indentation of the whole file is changed according to GitHub.
> 
> okay I will change the intention to original just to be clear I'm using this..
> 
> ```
> sorted_list = sorted(my_list)
> 
> for item in sorted_list:
>     print(f'"{item}",')
> 
> is_sorted = all(sorted_list[i] <= sorted_list[i+1] for i in range(len(sorted_list)-1))
> 
> print("Is the list sorted?", is_sorted)
> ```

@tjorim now I don't know it changed the order again.. anyhow print(f'12"{item}",') was used so the intention should be same as the original. If this once again is creating a blocking point for you guys please just reject it and I will do it again for next week.

**Pull request closed without merging**
