### PR TITLE
Adds new integration [dgomes/ha_erse]

### PR DESCRIPTION
**Pull request by dgomes**
New integration that automates tariff change of energy utility_meters in Portugal in accordance to oficial plans publish by the national entity ERSE

Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by dgomes** [comment]
Pretty sure the  `hacs.json` file is present :(

**Comment by ludeeus** [comment]
It is, but it's not valid JSON https://jsonlint.com/

**Comment by dgomes** [comment]
Thanks for pointing out! 

Fixed

**Comment by dgomes** [comment]
Tks!

**Pull request merged**
