### PR TITLE
Adds new integration [lorenzo-deluca/homeassistant-silence]

### PR DESCRIPTION
**Pull request by lorenzo-deluca**
**Link to successful HACS action:**  
**Link to successful hassfest action (if integration):**

### CODE REVIEW

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/publish/include#before-submitting

**Comment by ludeeus** [comment]
You can once both actions are successful in your repo

**Comment by lorenzo-deluca** [comment]
You're right, sorry.. Yes, I add action/hassfest and now it's ok https://github.com/lorenzo-deluca/homeassistant-silence/actions/runs/3733654749/jobs/6334717421

**Review by lorenzo-deluca — COMMENTED** [review]
Fix CI on hacs repository

**Pull request closed without merging**
