### PR TITLE
Adds new plugin [sopelj/lovelace-kanji-clock-card]

### PR DESCRIPTION
**Pull request by sopelj**
A card for Lovelace that displays a clock using Japanese Kanji for date and time. 
I know it's a bit niche, so I hope it's ok. I just thought others might enjoy it too.

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
Your hacs.json file needs a `country` key https://hacs.xyz/docs/publish/start#hacsjson

**Comment by sopelj** [comment]
For sure! Sorry, I thought it was optional. 
This may be a dumb question, but what country? Mine (CA)? Or should I put Japan (JP).
I thought this may just have been for region locked integrations/entities.

**Comment by ludeeus** [comment]
jp is probably most fitting here, since it's in that language

**Comment by sopelj** [comment]
OK, that makes sense. Thank you!
I've added it

**Pull request merged**
