### PR TITLE
Adds new integration [ofalvai/home-assistant-candy]

### PR DESCRIPTION
**Pull request by ofalvai**

### CODE REVIEW

**Comment by ofalvai** [comment]
PR merged in brands repo: https://github.com/home-assistant/brands/pull/2884
Wheels ready too: https://github.com/home-assistant/wheels-custom-integrations/pull/517

**Comment by ofalvai** [comment]
@ludeeus thank you for the merge!

I see that the hassfest check is failing, and I also noticed that the same GitHub Action started failing in my own repo too. Is this a bug in hassfest maybe? I see that you made changes to the script a few weeks ago, I'm not sure if I'm supposed to use dependency version ranges now or it's a legit failure that I should fix.

**Comment by ludeeus** [comment]
It's a bug in hassfest, which is why I ignored it here.

**Comment by ofalvai** [comment]
Is there any existing GH issue I can subscribe to, or should I open one?

**Comment by ludeeus** [comment]
<https://github.com/home-assistant/core/pull/59470>

**Pull request merged**
