### PR TITLE
Adds new integration [kodi1/songpal_m]

### PR DESCRIPTION
**Pull request by kodi1**
Before you submit a pull request, please make sure you have the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository

### CODE REVIEW

**Comment by ludeeus** [comment]
What is the difference between this adn https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/songpal?

**Comment by kodi1** [comment]
On some devices like sound bar "HT-MT500/501", volume decrease is not work out of the box.
This is workaround for https://github.com/rytilahti/python-songpal/issues/7

**Comment by ludeeus** [comment]
Why have a custom_component and not submit a PR to Home Assistant with the changes?
Also, your README should state the difference between them.

**Comment by kodi1** [comment]
According author of original component, the issue is in a firmware. So we still waiting for update.

**Comment by rytilahti** [comment]
See https://github.com/home-assistant/core/pull/36152

**Pull request merged**
