### PR TITLE
Adds new integration [Wibias/hass-variables]

### PR DESCRIPTION
**Pull request by Wibias**

### CODE REVIEW

**Comment by Wibias** [comment]
Not sure what I am doing wrong and why the checks are not running

**Comment by gjohansson-ST** [comment]
> Not sure what I am doing wrong and why the checks are not running

As you have not contributed before it requires a maintainer to approve the workflows to kick-off checking.

**Comment by Wibias** [comment]
Ah, that makes sense then. I was confused why some PR's are automatically checked after they get requested. But they were Contributors. So I am going to wait!

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

**Comment by Wibias** [comment]
Oops forgot about that. Pull request is in progress. https://github.com/home-assistant/brands/pull/2633

**Comment by Wibias** [comment]
Oops was that review request thing that one thing that we shouldn't do? If yes I am sorry about that. I am kinda new to this.

**Comment by Wibias** [comment]
Reverting the domain name concerning the brand icon is an open pull request right now. https://github.com/home-assistant/brands/pull/2635

**Pull request merged**
