### PR TITLE
Adds new integration [amitfin/patch]

### PR DESCRIPTION
**Pull request by amitfin**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/amitfin/patch/releases/tag/v1.1.1
Link to successful HACS action (without the `ignore` key): https://github.com/amitfin/patch/actions/runs/6463495942/job/17546742448
Link to successful hassfest action (if integration): https://github.com/amitfin/patch/actions/runs/6463495942/job/17546742580

### CODE REVIEW

**Comment by ludeeus** [comment]
I'm not going to allow this.
<https://hacs.xyz/docs/publish/include>
> Custom integrations that override core integrations will not be accepted, you can still use it as a [custom repository](https://hacs.xyz/docs/faq/custom_repositories)

Not only will this be used to override core integrations, it will also be done persistently without any possibility of detection, or warning. This will also bypass safe mode (which is designed to start core without any custom modifications).

For libraries I suggest <https://developers.home-assistant.io/docs/creating_integration_manifest?_highlight=deps#custom-requirements-during-development--testing> instead, as for core integration modifications you want to try, you can use custom components.

**Comment by amitfin** [comment]
Ok, fair enough.

Just for the records, this integration was developed for solving a real blocker:

- We have [Pima Force 144](https://www.pima-alarms.com/our-products/force-security-system/) alarm system.
- [SIA](https://www.home-assistant.io/integrations/sia) built-in integration supports its protocol, but requires handling 2 additional op codes.
- A [straightforward PR](https://github.com/eavanvalkenburg/pysiaalarm/pull/55/files) was created for enhancing the supporting library ([pysiaalarm](https://github.com/eavanvalkenburg/pysiaalarm)) with the additional 2 op codes. It's still waiting to be reviewed (or noticed). The PR was created on 12/Sep/2023, so it's more than 100 days old by now.
- This is not a testing environment. We use the integration in many home automation scenarios by now.
- Without this (Patch) integration there was no way to connect the alarm system to HA until the PR is accepted (which can be months or years from now).

Anyway, as mentioned above, there is no real need to add the integration to HACS. It's still possible to use HACS as the installer via [custom repository](https://hacs.xyz/docs/faq/custom_repositories).

**Comment by amitfin** [comment]
BTW, I'll be glad to learn if there is a better solution for the blocker...

**Comment by ludeeus** [comment]
The link to the developer docs I shared can be used for that.
Instead of a version, you can tell it to install from a git branch (explained other places in the dev docs (on mobile now so not easy to look up) I have used that way myself a few times)

**Comment by amitfin** [comment]
This is a production environment of [HAOS on RPI4](https://www.home-assistant.io/installation/raspberrypi).
Is it possible to add switches to the `hass` command in this environment? (`--skip-pip-packages pysiaalarm`)

**Comment by ludeeus** [comment]
I do not think so, but should not be needed.
That's mainly to prevent conflicts in venvs, for the container installs (all but core) the libs are already present.

You may need to install it to the root of your config instead of in the deps directory inside it.
Can't look up exactly how the loading order is.

**Pull request closed without merging**
