### PR TITLE
Adds new integration [Sennevds/media_player.template]

### PR DESCRIPTION
**Pull request by Sennevds**

### CODE REVIEW

**Comment by KTibow** [comment]
Create a new release and ask @hacs-bot to recheck.

**Comment by Sennevds** [comment]
/recheck
Aha didn't know it checked the release zip instead of the repo itself

**Comment by Sennevds** [comment]
If I add template as as a dependecy hass won't load my integration because template isn't a complete integration. If I leave it out hacs check fails what should I do with this?

**Comment by ludeeus** [comment]
Adding to  `after_dependencies` should be safe

**Comment by Sennevds** [comment]
Thanks for the fast response. That was the problem

**Comment by Sennevds** [comment]
closes Sennevds/media_player.template#1

**Pull request merged**
