### PR TITLE
Adds new integration [ollo69/ha-melcloud-custom]

### PR DESCRIPTION
**Pull request by ollo69**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by ludeeus** [comment]
Why have this as  a seperate custom_component and not just add it as a PR to Home Assistant?

**Comment by ollo69** [comment]
I create a PR to the creator of the library pyMelCloud to have some feature that I need to PR my change to the HA component, but he is don't magaging these. So I would like to start provide this additional feature to the comunity, I will PR to HA in the future.

**Comment by ollo69** [comment]
Some news about this PR?

**Comment by ludeeus** [comment]
For now, I can't accept more.
You can read more as for why and join the discussion here <https://discordapp.com/channels/606225571898327139/677520492508348416/694128528983064617>
When I have a solution I will go through all open PR's

**Comment by ollo69** [comment]
Close this for now and leave SmartThinQ Sensor open

**Pull request closed without merging**
