### PR TITLE
Adds new integration [basnijholt/adaptive-lighting]

### PR DESCRIPTION
**Pull request by basnijholt**
Brands PR https://github.com/home-assistant/brands/pull/1900

### CODE REVIEW

**Comment by basnijholt** [comment]
@ludeeus, the brands PR does actually exist at https://github.com/home-assistant/brands/pull/1900

Otherwise, the CI should pass now.

**Comment by ludeeus** [comment]
That PR is still open.
You already have a PR open for core, I'm not sure this should be added here as well, only to be removed later.
That will cause a lot of questions/issues when it's removed, and even if it's not in here, it can still be used for testing

**Comment by basnijholt** [comment]
> You already have a PR open for core, I'm not sure this should be added here as well, only to be removed later.

That is true, but that PR has been open for about three months and hasn't received any review from a core dev. I can imagine it will take months more before it is merged. This gives people a good way to try it and gives me the opportunity to squeeze out all the bugs before it makes it to core :)

**Comment by ludeeus** [comment]
Like I said, it can still be used without the addition here?
And without a merged brands PR, it will not be accepted here.

**Pull request closed without merging**
