### PR TITLE
Adds new integration [tellerbop/havistapool]

### PR DESCRIPTION
**Pull request by tellerbop**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by tellerbop** [comment]
Do not understand why it fails checking if the manifest.json file exists as it is there in the correct path....

**Comment by ludeeus** [comment]
The `hacs-bot` checks are partially broken, ignore it.
Focus on the other failed checks instead.

**Comment by tellerbop** [comment]
Well now i fixed the icon as suggested but that check still fails.

**Comment by ludeeus** [comment]
it failed 17h ago ;)
<https://hacs.xyz/docs/publish/include#ci-checks> see the note here about reruns.

**Pull request merged**
