### PR TITLE
Adds new integration [imicknl/ha-tahoma]

### PR DESCRIPTION
**Pull request by iMicknl**

### CODE REVIEW

**Comment by ludeeus** [comment]
Ignore this check, it is not needed (and it's wrong):
> Checks / Check Owner (pull_request) Failing after 16s — Check Owner

**Comment by iMicknl** [comment]
**Check Brands** does fail.
`tahoma` is not in custom_components, but it does exist in core_integrations. ([link](https://github.com/home-assistant/brands/tree/master/core_integrations/tahoma))

**Check Owner** fails
##[error]'iMicknl' is not a major contributor to 'imicknl/ha-tahoma'
@tetienne / @vlebourl could you sign off here as well? <3

**Comment by ludeeus** [comment]
You can ignore both those then

**Comment by iMicknl** [comment]
Opened https://github.com/home-assistant/wheels-custom-integrations/pull/114 to solve remaining check **Checks / Check Wheels**.

**Comment by iMicknl** [comment]
**Check Brands** and **Check Owner** are currently failing, however they should be ignored. PR is ready for review.

cc @ludeeus

**Comment by ludeeus** [comment]
Can you rebase this?
I think both tests are fixed in master now

**Comment by iMicknl** [comment]
> Can you rebase this?
> I think both tests are fixed in master now

Done!

It looks like you accidentally hardcod

**Pull request merged**
