### PR TITLE
Adds new integration [lolouk44/CurrentCost_HA_CC]

### PR DESCRIPTION
**Pull request by lolouk44**
adding current cost custom integration

### CODE REVIEW

**Comment by lolouk44** [comment]
yeah all checks passed 👍 Quick Q if someone can help:
Now that i've realised hacs.json is case sensitive, are other files too? (README, INFO, etc)

**Comment by ludeeus** [comment]
They are not <https://github.com/hacs/default/pull/613/checks?check_run_id=1100931740#step:5:8>

**Comment by lolouk44** [comment]
Thanks @ludeeus for your help, much appreciated
And thank you for HACS, I use it a lot and hopefully my contribution helps others too :)

**Comment by lolouk44** [comment]
Just checking in case I missed something: am I due to do something or do I just need to wait for this PR to be merged?

**Comment by ludeeus** [comment]
3 notes.

You have an `info.md` file but in `hacs.json` you have `"render_readme": true,` so that file is not used for anything.
The directory that your integration is in should match the domain name, so the directory should be renamed from  `CurrentCost_HA_CC` to `currentcost`

You should also create a new release after adjustments

**Comment by lolouk44** [comment]
thanks @ludeeus 
All done now

**Comment by ludeeus** [comment]
Was not really needed to be included, but it looked weird :smile:

**Comment by lolouk44** [comment]
Yeah ! 
Guess I now need to brace myself for change requests from users who want it done differently 😆

**Comment by ludeeus** [comment]
Nah, now you follow a "standard" that is in use by most other integrations, they should not have an issue with it.

**Comment by lolouk44** [comment]
yes, I've pretty much cloned the `serial` integration.
The only think I need to learn is how to generate entities automatically / dynamically based on the data I read from the serial port.
Taking it all one step at a time.
For now I'm glad I've just managed to "pull this off" by having my first "semi" official HA integration 😄

**Pull request merged**
