### PR TITLE
Adds new integration [travisghansen/hass-pfsense]

### PR DESCRIPTION
**Pull request by travisghansen**
Signed-off-by: Travis Glenn Hansen <travisghansen@yahoo.com>

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass.
https://hacs.xyz/docs/publish/include#before-submitting

**Comment by travisghansen** [comment]
Yeah I just added a dep that needs to go to wheels..should be cleaned up soon enough!

**Comment by travisghansen** [comment]
We should be good to go now.

For reference: https://github.com/home-assistant/wheels-custom-integrations/pull/533

**Comment by ludeeus** [comment]
Should be double good to go now.

For refrence: 
- https://github.com/hacs/action/commit/e57bf7bf28ce309660b45f94e2c1c7583e10bb18
- https://github.com/hacs/documentation/commit/b74997034fbec3cbd56b3fed538d02df4b825555

**Comment by travisghansen** [comment]
Thanks!

**Pull request merged**
