### PR TITLE
Adds new integration [jwillemsen/daikin_onecta]

### PR DESCRIPTION
**Pull request by jwillemsen**
Migrated daikin_residential_altherma to my fork, original maintainer seems unresponsive

## Checklist

- [X] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [X] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [X] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [X] The actions are passing without any disabled checks in my repository.
- [X] I've added a link to the action run on my repository below in the links section.
- [X] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/jwillemsen/daikin_onecta/releases/tag/v4.0.7
Link to successful HACS action (without the `ignore` key): https://github.com/jwillemsen/daikin_onecta/actions/runs/8171360465
Link to successful hassfest action (if integration): https://github.com/jwillemsen/daikin_onecta/actions/runs/8084840999

### CODE REVIEW

**Comment by tjorim** [comment]
Don't remove and add a repo in one PR.

**Comment by jwillemsen** [comment]
> Don't remove and add a repo in one PR.

Thanks for letting me know, made this PR just an addition

**Comment by jwillemsen** [comment]
Waiting on logo merge through PR https://github.com/home-assistant/brands/pull/5232

**Comment by jwillemsen** [comment]
daikin_onecta logo is now available, so removed the draft setting

**Pull request merged**
