### PR TITLE
Adds new integration [syssi/xiaomi_airpurifier]

### PR DESCRIPTION
**Pull request by syssi**
Wheels PR: https://github.com/home-assistant/wheels-custom-integrations/pull/158
Brands PR: https://github.com/home-assistant/brands/pull/1940

### CODE REVIEW

**Comment by KTibow** [comment]
Mind adding topics? Try
- home-assistant
- homeassistant
- xiaomi
- python
- python3

**Comment by syssi** [comment]
Topics added.

**Review by zigul — APPROVED** [review]

**Pull request merged**
