### PR TITLE
Adds new integration [konnected-io/noonlight-hass]

### PR DESCRIPTION
**Pull request by snicker**
this adds the noonlight integration for HomeAssistant developed by Konnected

Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by snicker** [comment]
@heythisisnate is the repository owner I believe and can back me up here on getting this merged in.

**Comment by heythisisnate** [comment]
excellent! Thanks @snicker

**Comment by heythisisnate** [comment]
hey @snicker @ludeeus what can we do to move this along?

**Comment by ludeeus** [comment]
Speed up time, I will not be merging anything until Sunday (UTC).
It's explained fairly well on the #publishers channel on discord if you want to know more.
https://discord.gg/apgchf8

**Comment by ludeeus** [comment]
Needs a rebase.
I tried to do it, but you have blocked reviewer access...

**Comment by snicker** [comment]
rebased

**Pull request merged**
