### PR TITLE
Adds new integration [Antoni-Czaplicki/vulcan-for-hassio]

### PR DESCRIPTION
**Pull request by Antoni-Czaplicki**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
The library you use installs `asyncio` from PyPi, which it should not, that is a standard lib in Python.

**Comment by Antoni-Czaplicki** [comment]
@ludeeus is there any other option to change this other than removing this dependency from the API?

**Comment by ludeeus** [comment]
You have to take that up with the owner of that library

**Review by ludeeus — CHANGES_REQUESTED** [review]
This service is only available in a single country, add the country key to hacs.json

**Review by ludeeus — APPROVED** [review]

**Pull request merged**
