### PR TITLE
Adds new integration [bdunn44/hass-jellyfish-lighting]

### PR DESCRIPTION
**Pull request by bdunn44**
**Link to successful HACS action: https://github.com/bdunn44/hass-jellyfish-lighting/actions/runs/4272155249/jobs/7437103699**  
**Link to successful hassfest action (if integration): https://github.com/bdunn44/hass-jellyfish-lighting/actions/runs/4272155249/jobs/7437103699**

### CODE REVIEW

**Comment by ludeeus** [comment]
https://github.com/bdunn44/hass-jellyfish-lighting/actions/runs/4267240219

**Comment by bdunn44** [comment]
@ludeeus noooooo! Worst timing... this just started failing a couple of days ago. Must be a new check. I'll look into it.

**Comment by bdunn44** [comment]
@ludeeus new manifest sorting rule caused validation to fail. It's passing now - marking this as ready for review.

https://github.com/bdunn44/hass-jellyfish-lighting/actions/runs/4272155249/jobs/7437103699

**Comment by ludeeus** [comment]
<https://github.com/bdunn44/hass-jellyfish-lighting/blob/master/.devcontainer/devcontainer.json#L3>
You should move away from that ([reason](https://github.com/ludeeus/container#deprecated)).
Example for an alternative:
- [`.devcontainer.json`](https://github.com/ludeeus/integration_blueprint/blob/main/.devcontainer.json)
- [scripts dir instead of `container` CLI](https://github.com/ludeeus/integration_blueprint/tree/main/scripts)

**Pull request merged**
