### PR TITLE
Adds new integration [pinkywafer/Calendarific]

### PR DESCRIPTION
**Pull request by pinkywafer**
Before you submit a pull request, please make sure you have the following:

- [x] You are submitting only 1 repository.
- [x] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository

### CODE REVIEW

**Comment by pinkywafer** [comment]
Added topics to repo... anything else missing?

**Comment by ludeeus** [comment]
The checklist 
image

**Comment by pinkywafer** [comment]
Ok to edit PR? or need a new?

**Comment by ludeeus** [comment]
edit when you are ready

**Comment by pinkywafer** [comment]
Done

**Pull request merged**
