### PR TITLE
Adds new integration [rexave/hass-orange-internet-on-the-move]

### PR DESCRIPTION
**Pull request by rexave**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start)
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/)
- [x] The actions are passing wihtout any disabled checks
- [x] I've added a link to the action run on my repository below
- [x] I've created a new release of the repository after the validaaion actions were run successfully

## Links

Link to current release: https://github.com/rexave/hass-orange-internet-on-the-move/releases/tag/0.1.0
Link to successful HACS action (without the 'ignore' key): https://github.com/rexave/hass-orange-internet-on-the-move/actions/runs/4158489484
Link to successful hassfest action (if integration): https://github.com/rexave/hass-orange-internet-on-the-move/actions/runs/4158489483

### CODE REVIEW

**Comment by rexave** [comment]
do i need to do something else to make this request approved ?

**Comment by ludeeus** [comment]
https://github.com/rexave/hass-orange-internet-on-the-move/actions/runs/4267719803

**Comment by rexave** [comment]
fixed ! @ludeeus

**Comment by ludeeus** [comment]
image

**Comment by rexave** [comment]
had some dificulties to understand what was wrong.
I think you ask for a new release ?
I didn't do it because it was only the json order of manifest.json
Anyway, i finally did it : https://github.com/rexave/hass-orange-internet-on-the-move/releases/tag/0.1.1

and here are the checks : 
https://github.com/rexave/hass-orange-internet-on-the-move/actions/runs/4589502159
https://github.com/rexave/hass-orange-internet-on-the-move/actions/runs/4589502160

please tell me if there anything else i should do

**Comment by rexave** [comment]
@ludeeus can you reopen this PR or should i create a new one ?

**Comment by ludeeus** [comment]
Create a new one when it's actually ready.

**Comment by rexave** [comment]
ok thank you for your answer.
Here is the new one : https://github.com/hacs/default/pull/1823
Hope it will be ok now :), thank for your time !

**Pull request closed without merging**
