### PR TITLE
Adds new integration [benleb/sureha]

### PR DESCRIPTION
**Pull request by benleb**
Hey Jo,

this is a variant of https://github.com/hacs/default/pull/929 which you declined due to the absolute stupid naming. I fixed that everywhere, see https://github.com/benleb/sureha#naming-confusion-for-surepetcarebeta-users--- for example :)

Thanks!

### CODE REVIEW

**Comment by jbouwh** [comment]
@benleb could you have a look why the Python wheels fails here? (more-info: https://hacs.xyz/docs/publish/include#check-wheels )

**Comment by benleb** [comment]
I probably know the problem ;) The check ran bevor [this PR](https://github.com/home-assistant/wheels-custom-integrations) was merged. Can you please re-run the check, I expect it to be passed now :)

**Comment by benleb** [comment]
@ludeeus what's the idea behind users are allowed to retrigger the checks but to run they still ned to be approved manually?

**Comment by ludeeus** [comment]
you have to ask github about that.... https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

**Pull request merged**
