### PR TITLE
Adds new integration [elden1337/hass-peaqhvac]

### PR DESCRIPTION
**Pull request by elden1337**
**Link to successful HACS action:**  
**Link to successful hassfest action (if integration):**

### CODE REVIEW

**Comment by elden1337** [comment]
To reviewers: 
Unsure why the HACS-action runner fails as the faulty keys "domains" where removed several hours before this PR was created. This is the current state of the file.

```json
{
  "name": "Peaqhvac",
  "homeassistant": "2022.10.5",
  "zip_release": true,
  "filename": "peaqhvaq.zip",
  "render_readme": true
}
```

Your call, I dunno if you'd rather have me close this and re-open or other solutions are possible?

**Comment by tjorim** [comment]
The CI pulls the latest release AFAIK. Did you create a release after changing the file?

**Comment by elden1337** [comment]
Aha! Good catch. Thought it just pulled the repo.

**Pull request merged**
