### PR TITLE
Adds new integration [fsaris/home-assistant-zonneplan-one]

### PR DESCRIPTION
**Pull request by fsaris**

### CODE REVIEW

**Comment by fsaris** [comment]
Can anyone explain why the `HACS Action` fails here but is successful on my own repo? https://github.com/fsaris/home-assistant-zonneplan-one/runs/2005035760#step:3:150

**Comment by fsaris** [comment]
> Can anyone explain why the `HACS Action` fails here but is successful on my own repo? https://github.com/fsaris/home-assistant-zonneplan-one/runs/2005035760#step:3:150

Ok, after tagging a new release with all required changes for hacs support the check now succeeds 😄 

Probably it pulled the 0.0.1 version before that didn't have the hacs.json file yet.

**Review by markgdev — APPROVED** [review]

**Pull request merged**
