### PR TITLE
Removes ziggonext integration from default repository

### PR DESCRIPTION
**Pull request by Sholofly**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
<https://hacs.xyz/docs/publish/remove>
This is missing changes

**Comment by Sholofly** [comment]
Ah i see, i need to execute the make command. I'm running windows 10. Do you know how i can execute make command from windows?

**Comment by ludeeus** [comment]
<https://github.com/hacs/integration/issues/new?assignees=ludeeus&labels=flag&template=removal.yml> Fill out that instead and I'll take care of it

**Comment by Sholofly** [comment]
Check! TY!

**Pull request closed without merging**
