### PR TITLE
Adds new integration [ryanwinter/hass-rainforest-emu-2]

### PR DESCRIPTION
**Pull request by ryanwinter**

### CODE REVIEW

**Comment by ryanwinter** [comment]
brands PR: https://github.com/home-assistant/brands/pull/3239

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass 
https://hacs.xyz/docs/publish/include#before-submitting

**Comment by ryanwinter** [comment]
> CI does not pass https://hacs.xyz/docs/publish/include#before-submitting

Done

**Review by ryanwinter — COMMENTED** [review]
fixed

**Pull request merged**
