### PR TITLE
Remove rsnodgrass

### PR DESCRIPTION
**Pull request by ludeeus**
Ref: https://hacs.xyz/docs/publish/remove

@rsnodgrass please restore your deleted repositories or I will need to merge this in 24h.

### CODE REVIEW

**Comment by rsnodgrass** [comment]
Resolved, sorry about that! Accidentally marked two as private repo when doing some cleanup yesterday.

**Comment by rsnodgrass** [comment]
Fixed

**Comment by ludeeus** [comment]
Thanks 👍

**Comment by rsnodgrass** [comment]
@ludeeus fixed! Sorry about that, was an accident.

**Comment by rsnodgrass** [comment]
Somehow this also kicked me out of the HACS organization on github. Can you restore that as well?  Thanks.

**Comment by ludeeus** [comment]
That's unrelated, everyone that does not need it will be removed.
Users were added in hope to help with queue in this repo, but that I still do, and it's not worth potential security implications by having more than needed users in the org.

**Pull request closed without merging**
