### PR TITLE
Adds new integration [ciejer/metservice-weather]

### PR DESCRIPTION
**Pull request by ciejer**
## Checklist

- [X] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [X] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [X] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [X] The actions are passing without any disabled checks in my repository.
- [X] I've added a link to the action run on my repository below in the links section.
- [X] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/ciejer/metservice-weather/releases/tag/v0.1.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/ciejer/metservice-weather/actions/runs/6611963573/job/17956866020>
Link to successful hassfest action (if integration): <https://github.com/ciejer/metservice-weather/actions/runs/6611963573/job/17956865758>

### CODE REVIEW

**Comment by tjorim** [comment]
Is this integration limited to New Zealand?

**Comment by ciejer** [comment]
Integration will work elsewhere, but forecasts from MetService are New Zealand specific

**Comment by tjorim** [comment]
Since it will only get the weather forecast for places in NZ I would suggest adding the country code: https://hacs.xyz/docs/publish/start/#hacsjson

**Comment by ciejer** [comment]
Updated in 0.1.1 release, thank you

**Comment by ciejer** [comment]
Will reopen once brand added

**Pull request closed without merging**
