### PR TITLE
Removing unmaintained and broken integration

### PR DESCRIPTION
**Pull request by troykelly**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
This is not enough, you need to run the remove script for a full cleanup <https://hacs.xyz/docs/publish/remove#remove-a-repository>

**Comment by troykelly** [comment]
@ludeeus Forgive me - possibly lost in translation - but to understand the warning on the page, you expect any repository added to `HACS` to be maintained forever, to never get deprecated, and if it does - you blacklist the owner of the repository?
That isn't very friendly.

**Comment by ludeeus** [comment]
Not at all, that's about deleting their repository of GitHub. I expect the author to open a PR to remove it before they do that or notify me in any way so I can do it.

Archiving or other forms of deprecations are fine.

**Comment by troykelly** [comment]
> Not at all, that's about deleting their repository of GitHub. I expect the author to open a PR to remove it before they do that or notify me in any way so I can do it.
> 
> Archiving or other forms of deprecations are fine.

Apologies. I thought I was doing the right thing removing it from integrations given somebody else had written a (far better) integration than mine.

I've created a PR using the `make remove` tool. Thank you for letting me know.

**Comment by ludeeus** [comment]
What you did here <https://github.com/troykelly/hacs-amberelectric> is perfect :+1: 

This however is removed/deleted from github <https://github.com/USA-RedDragon/badnest> that's just bad for everyone :-1:

**Comment by ludeeus** [comment]
Replaced by <https://github.com/hacs/default/pull/1025>

**Pull request closed without merging**
