### PR TITLE
Adds new integration [mbillow/ha-chargepoint]

### PR DESCRIPTION
**Pull request by mbillow**
Add ChargePoint custom integration to default repos.

### CODE REVIEW

**Comment by ludeeus** [comment]
There are no instructions on how to use it.

**Comment by mbillow** [comment]
> There are no instructions on how to use it.

Updating the README was actually on my todo list today. It really is just as simple and installing and logging in, though. 

Is there anywhere else that documentation needs to be?

**Comment by mbillow** [comment]
I added installation, usage, and development instructions to the README. Let me know if there is anything else you want/need here.

**Pull request merged**
