### PR TITLE
Adds new integration [myTselection/bibliotheek_be]

### PR DESCRIPTION
**Pull request by myTselection**
repo myTselection/bibliotheek_be with custom integration to retrieve library info of all Belgin Flemish libraries with loan info and services to extend loan

**Link to successful HACS action:**  https://github.com/myTselection/bibliotheek_be/actions/workflows/hacs_action.yml
**Link to successful hassfest action (if integration):**  https://github.com/myTselection/bibliotheek_be/actions/workflows/hassfest_validation.yml

### CODE REVIEW

**Comment by ludeeus** [comment]
https://github.com/myTselection/bibliotheek_be/actions/runs/4267380952

**Comment by myTselection** [comment]
all fixed https://github.com/myTselection/bibliotheek_be/actions/workflows/hacs_action.yml

**Comment by myTselection** [comment]
Hi, can you please approve or indicate which action I can take to comply? thanks a lot!

**Comment by myTselection** [comment]
should I close and relauch this request? not clear why it's not picked up while other new pull requested are treated... let me know if I  need to fix anything.

**Comment by tjorim** [comment]
It's because you keep merging the master branch and adding comments, that only pushes it back to the list: https://github.com/hacs/default/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-asc+draft%3Afalse

**Comment by myTselection** [comment]
:) 
not sure if that's the reason, I've left it untouched for a while too so I tought it was cause by being out of sync with the master branch. I'll leave it untouched again for a while and else I might close this PR and launch a new one to see if that helps.

**Comment by tjorim** [comment]
Ludeeus said that's the order he follows, currently it shows this PR last at #88.

**Comment by ludeeus** [comment]
<https://github.com/myTselection/bibliotheek_be/blob/master/custom_components/bibliotheek_be/__init__.py#L19> This is doing I/O during module import, which will hurt Home Assistant startup performance.
An alternative is to use this during the setup <https://github.com/home-assistant/core/blob/dev/homeassistant/loader.py#L892>

**Pull request merged**
