### PR TITLE
Adds new integration [bosch-thermostat/home-assistant-bosch-custom-component]

### PR DESCRIPTION
**Pull request by pszafer**

### CODE REVIEW

**Review by wowgamr — APPROVED** [review]
Looks like it's ok 👍

**Review by jugla — APPROVED** [review]

**Review by msekoranja — APPROVED** [review]

**Review by ludeeus — CHANGES_REQUESTED** [review]
Enable "Allow edits by maintainers" on the PR.

**Comment by pszafer** [comment]
> Enable "Allow edits by maintainers" on the PR.

@ludeeus any idea why I don't have such option in this PR?
It should be just below participants, right?

**Comment by ludeeus** [comment]
Usually it's there. maybe it's because you are using the `master` branch, could be they don't allow that.

**Comment by pszafer** [comment]
@ludeeus it seems it's kind of bug if I created fork under organization account.
https://github.com/isaacs/github/issues/1681

Anyway I see that I can either recreate this PR by creating new one with my account or I can give you admin access to this fork.
Which way should I proceed?

**Comment by ludeeus** [comment]
Close this PR and recreate it with your personal account

**Comment by pszafer** [comment]
ok, closing this. new PR https://github.com/hacs/default/pull/817

**Pull request closed without merging**
