### PR TITLE
Adds new integration [danielkaldheim/ha_airstage]

### PR DESCRIPTION
**Pull request by danielkaldheim**
## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/danielkaldheim/ha_airstage/releases/tag/v1.1.3
Link to successful HACS action (without the `ignore` key):  https://github.com/danielkaldheim/ha_airstage/actions/runs/6503172452
Link to successful hassfest action (if integration): https://github.com/danielkaldheim/ha_airstage/actions/runs/6502877441

### CODE REVIEW

**Comment by danielkaldheim** [comment]
Just became aware that if I merged towards master, I was pushed to the end of the list. This doesn't make sense? Just trying to keep the PR "warm".
You should add something about this in https://hacs.xyz/docs/publish/include/#after-submitting.

**Comment by tjorim** [comment]
It was included but it's not the case anymore. Don't understand why you want to keep it 'warm' tho.

**Comment by danielkaldheim** [comment]
I don't know, I thought updating the links to the most recent was a good thing, and why not merge or rebase the master into PR to keep it fresh while your checking the status of the pull requests.

I fully understand that there are many PR's and there must be some kind of a structure, and I'm very graceful that this repository exists and appreciate the work that is being done! 
But that it took me a while to understand that my PR was pushed down the line because of this just make me frustrated.

**Comment by ludeeus** [comment]
As of 2 weeks ago that is no longer the case.

**Comment by ludeeus** [comment]
<https://hacs.xyz/docs/publish/include>
> Custom integrations that exist to alpha/beta test core integrations will not be accepted, you can still use it as a [custom repository](https://hacs.xyz/docs/faq/custom_repositories)

<https://github.com/danielkaldheim/ha_airstage/issues/10>

**Pull request closed without merging**
