### PR TITLE
Adds new integration [robmarkcole/HASS-S3]

### PR DESCRIPTION
**Pull request by robmarkcole**
Before you submit a pull request, please make sure you have done the following:

- [x] You are submitting only 1 repository.
- [ ] You repository is compliant with https://hacs.xyz/docs/publish/start
- [x] You have tested it with HACS by adding it as a custom repository.
- [x] The list are still alphabetical after my change.

### CODE REVIEW

**Comment by robmarkcole** [comment]
The AWS brand could be used

**Comment by KTibow** [comment]
As the check said about the manifest:
Missing required value for key 'issue_tracker' in custom_components/s3/manifest.json
Mind fixing this @robmarkcole?

**Pull request closed without merging**
