### PR TITLE
Adds new integration [J-Lindvig/Flagdays_DK]

### PR DESCRIPTION
**Pull request by J-Lindvig**
Flagdays_dk is a integration which is scraping the official flagsdays.

It is possible to add your own flagdays, ex. birthdays or other signifacant events.
You can also specify which flags you own and wish to use.
Furthermore it uses a online API to calculate sunrise and sunset to be use in the flag_up and flag_down times.
If given an offset, it will create some extra attributes with the offset subtracted from the flag_up and flag_down times.

There are boolean switches stating if it is a memorial with special orders regarding the event.
image

### CODE REVIEW

**Comment by ludeeus** [comment]
Can you stop this?
You do not need to close and recreate.
<https://hacs.xyz/docs/publish/include#re-run-checks>
Thanks.

**Comment by ludeeus** [comment]
oh, and <https://hacs.xyz/docs/publish/include#before-submitting>

**Comment by J-Lindvig** [comment]
> oh, and https://hacs.xyz/docs/publish/include#before-submitting



> Can you stop this? You do not need to close and recreate. https://hacs.xyz/docs/publish/include#re-run-checks Thanks.

Got it and sorry for the inconvenience.

**Pull request merged**
