### PR TITLE
Adds new integration [Aohzan/ecodevices]

### PR DESCRIPTION
**Pull request by Aohzan**
Hello,

I add the [GCE Eco-Devices](https://github.com/Aohzan/ecodevices) integration

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass

**Comment by Aohzan** [comment]
Wait for https://github.com/home-assistant/wheels-custom-integrations/pull/412

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

**Comment by Aohzan** [comment]
tag 2.2.0 added with manifest file

**Pull request merged**
