### PR TITLE
Adds new integration [TheByteStuff/RemoteSyslog_Service]

### PR DESCRIPTION
**Pull request by TheByteStuff**
Adds new integration [TheByteStuff/RemoteSyslog_Service]

### CODE REVIEW

**Review by dreed47 — APPROVED** [review]

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass

**Comment by TheByteStuff** [comment]
updated hacs.json & manifest.json

**Comment by TheByteStuff** [comment]
updated manifest.json iot_class to "assumed_state"

**Pull request merged**
