### PR TITLE
Adds new integration [itchannel/fordpass-ha]

### PR DESCRIPTION
**Pull request by itchannel**

### CODE REVIEW

**Comment by itchannel** [comment]
Any ideas why the HACS check is failing as it works fine on my install and can't understand that error?

**Comment by KTibow** [comment]
I think that the `homeassistant` library isn't installed, or the frontend part of it wasn't.

**Review by djtimca — APPROVED** [review]

**Comment by KTibow** [comment]
Nope, actually HACS validation is broken, I'll try /recheck

**Pull request merged**
