### PR TITLE
Adds new integration [futuretense/keymaster]

### PR DESCRIPTION
**Pull request by FutureTense**
Added keymaster

EDIT from @raman325 : This is a replacement for an existing integration (lock-manager)

### CODE REVIEW

**Comment by FutureTense** [comment]
Check

**Review by djtimca — APPROVED** [review]

**Review by raman325 — APPROVED** [review]
since this is replacing lock-manager, you may want to consider submitting it for removal in the same PR

**Comment by FutureTense** [comment]
> since this is replacing lock-manager, you may want to consider submitting it for removal in the same PR

@raman325, I was just thinking of this.  How do I do this?

For those following this, the repo in question is [Lock-Manager](https://github.com/FutureTense/lock-manager) and the integration to is `"futuretense/lock-manager"`

Is this as simple as removing that line and deleting the integration folder?

**Comment by raman325** [comment]
Here are the steps I would take:

1. Update the [Lock-Manager](https://github.com/FutureTense/lock-manager) README to point to your new repo
2. Remove `futuretense/lock-manager` from the `integration` file
3. Potentially add `futuretense/lock-manager` to the `blacklist` file to signal to HACS that it should be uninstalled

**Review by FutureTense — COMMENTED** [review]
Perfect

**Comment by FutureTense** [comment]
What happens after we get that elusive last reviewer?  Will this automatically get merged?

**Review by ludeeus — CHANGES_REQUESTED** [review]
You can not replace it like this.
To remove a repository have a look here <https://hacs.xyz/docs/publish/remove>

**Comment by FutureTense** [comment]
@ludeeus ok, I understand.  I undid my removal of the existing integration and will follow the procedure you mentioned.  Is it possible for you to accept this new integration now?  I’m under a time crunch and want to leave my fellow developers on this in a good place.

**Pull request merged**
