### PR TITLE
Adds new integration [zha-ng/zha-map]

### PR DESCRIPTION
**Pull request by MTrab**

### CODE REVIEW

**Review by wowgamr — APPROVED** [review]
Looks like it's ok 👍

**Comment by MTrab** [comment]
@ludeeus ??

**Comment by ludeeus** [comment]
> DO NOT REQUEST REVIEWS, THAT IS JUST RUDE, IF YOU DO THE PULL REQUEST WILL BE CLOSED!

This is in the PR template, you requested review from 9! people

**Comment by MTrab** [comment]
You closed this PR some time ago, and marked it merged - but it isn't merged, hence I tagged you to get this fixed.

**Comment by ludeeus** [comment]
This is not tagged as merged.

**Comment by MTrab** [comment]
Okay - then I must have misunderstood something. But why was it closed then?

**Comment by ludeeus** [comment]
You did not follow the rules

**Comment by MTrab** [comment]
I apologize then - so a new PR, or?

**Comment by ludeeus** [comment]
yes

**Comment by MTrab** [comment]
Okay - not that I wan't to argue or anything, but a simple comment on why it was closed would have been super nice :/

**Pull request closed without merging**
