### PR TITLE
Adds new integration [Sha-Darim/brandriskute]

### PR DESCRIPTION
**Pull request by Sha-Darim**
I hope I got everything right :-)

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

**Comment by Sha-Darim** [comment]
> CI does not pass
> https://hacs.xyz/docs/publish/include/#before-submitting

If I understand what I got, validation is now OK

**Comment by Sha-Darim** [comment]
@ludeeus 
I'm doing this for the first time, I hope I got everything right now. If not, can you please point me in the right direction?
Tack!

**Review by ludeeus — CHANGES_REQUESTED** [review]
This needs `country` set in  `hacs.json` https://hacs.xyz/docs/publish/start#hacsjson

**Comment by Sha-Darim** [comment]
@ludeeus 
OK, updated hacs.json - added country.

**Pull request merged**
