### PR TITLE
Adds new integration [mullerdavid/hass_GreeExt]

### PR DESCRIPTION
**Pull request by mullerdavid**
Please add my custom component for extending gree climate components with swing mode service.
As it is using the builtin gree integration, wheel and brands tests were disabled in the automatic workflow checks.

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

**Comment by mullerdavid** [comment]
> CI does not pass
> https://hacs.xyz/docs/publish/include/#before-submitting

As I indicated earlier, the wheel and brand tests are disabled. They are the failed ones. 

What should be the solution to resolve this? I can remove the dependency to skip the wheels test, as it is guaranteed to be installed, but I can't use the existing brand name/domain. Adding it to brand images again doesn't make sense.

**Comment by ludeeus** [comment]
It's an independent integration, these things are needed

**Comment by mullerdavid** [comment]
Added the icons and removed the requirement as the dependency has them. Should pass the checks now.

**Pull request merged**
