### PR TITLE
Removed Integration briis/smartweather

### PR DESCRIPTION
**Pull request by briis**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
This changes more than it should

**Comment by briis** [comment]
I followed the procedure [outlined here](https://hacs.xyz/docs/publish/remove) and the `make remove` command changed these files. So what is wrong?

Basically I just want to remove `briis/smartweather` as this has been replaced with a new Integration.

**Comment by ludeeus** [comment]
That is the way, it looks like you have used an additional formatter on the `removed` file
You can try `make sort`

**Comment by briis** [comment]
I will close this and start all over again.

**Pull request closed without merging**
