### PR TITLE
Adds new integration [rt400/Jewish-Sabbaths-Holidays]

### PR DESCRIPTION
**Pull request by rt400**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
CI does not pass

**Comment by rt400** [comment]
> CI does not pass

i run check again and its OK

**Review by ludeeus — CHANGES_REQUESTED** [review]
<https://github.com/rt400/Jewish-Sabbaths-Holidays/blob/master/custom_components/hebcal/manifest.json#L2> that's not correct

**Comment by rt400** [comment]
> https://github.com/rt400/Jewish-Sabbaths-Holidays/blob/master/custom_components/hebcal/manifest.json#L2 that's not correct

i can't understand what the problem

**Comment by ludeeus** [comment]
https://github.com/hacs/default/pull/902/checks?check_run_id=2575781523#step:7:25
https://developers.home-assistant.io/docs/creating_integration_manifest#iot-class

**Comment by rt400** [comment]
> https://github.com/hacs/default/pull/902/checks?check_run_id=2575781523#step:7:25
> https://developers.home-assistant.io/docs/creating_integration_manifest#iot-class

OK, thanks for helping. i fix it . can you check it again plz ?

**Comment by rt400** [comment]
@ludeeus can you plz check it ?

**Pull request merged**
